const REPORT = {
  record: { w:31, l:20 },
  weekSummary: {
    record: "3-2",
    runsScored: 14,
    runsAllowed: 12,
    notes: [
      "Auto-updated from MLB Stats API for games 2026-05-18 to 2026-05-24.",
      "Padres outscored opponents 14-12 over 5 finalized game(s)."
    ],
    teamOps: ".658"
  },
  roster: [
    {
      id: "tatis",
      name: "Fernando Tatis Jr.",
      position: "RF",
      hand: "R/R",
      stats: {
        G: 50,
        AVG: ".238",
        OBP: ".319",
        SLG: ".276",
        OPS: ".595",
        HR: 0,
        RBI: 16,
        SB: 12
      }
    },
    {
      id: "merrill",
      name: "Jackson Merrill",
      position: "CF",
      hand: "L/R",
      stats: {
        G: 48,
        AVG: ".206",
        OBP: ".278",
        SLG: ".328",
        OPS: ".606",
        HR: 4,
        RBI: 19,
        SB: 10
      }
    },
    {
      id: "machado",
      name: "Manny Machado",
      position: "3B",
      hand: "R/R",
      stats: {
        G: 49,
        AVG: ".176",
        OBP: ".271",
        SLG: ".341",
        OPS: ".612",
        HR: 8,
        RBI: 24,
        SB: 1
      }
    },
    {
      id: "bogaerts",
      name: "Xander Bogaerts",
      position: "SS",
      hand: "R/R",
      stats: {
        G: 49,
        AVG: ".243",
        OBP: ".311",
        SLG: ".379",
        OPS: ".690",
        HR: 7,
        RBI: 24,
        SB: 7
      }
    },
    {
      id: "arraez",
      name: "Luis Arraez",
      position: "2B",
      hand: "L/R",
      stats: {
        G: 35,
        AVG: ".309",
        OBP: ".356",
        SLG: ".377",
        OPS: ".733",
        HR: 2,
        RBI: 13,
        SB: 1
      }
    },
    {
      id: "campusano",
      name: "Luis Campusano",
      position: "C",
      hand: "R/R",
      stats: {
        G: 28,
        AVG: ".276",
        OBP: ".332",
        SLG: ".471",
        OPS: ".803",
        HR: 6,
        RBI: 23,
        SB: 0
      }
    },
    {
      id: "france",
      name: "Ty France",
      position: "1B",
      hand: "R/R",
      stats: {
        G: 31,
        AVG: ".268",
        OBP: ".302",
        SLG: ".500",
        OPS: ".802",
        HR: 4,
        RBI: 15,
        SB: 1
      }
    },
    {
      id: "sheets",
      name: "Gavin Sheets",
      position: "1B",
      hand: "L/L",
      stats: {
        G: 47,
        AVG: ".254",
        OBP: ".333",
        SLG: ".514",
        OPS: ".847",
        HR: 9,
        RBI: 23,
        SB: 3
      }
    },
    {
      id: "king",
      name: "Michael King",
      position: "P",
      hand: "R/R",
      stats: {
        G: 10,
        GS: 10,
        W: 4,
        ERA: "2.31",
        WHIP: "1.06",
        IP: "58.1",
        K: 59,
        BB: 24,
        SV: 0,
        HLD: 0,
        BS: 0
      }
    },
    {
      id: "buehler",
      name: "Walker Buehler",
      position: "P",
      hand: "R/R",
      stats: {
        G: 10,
        GS: 10,
        W: 3,
        ERA: "5.05",
        WHIP: "1.40",
        IP: "46.1",
        K: 41,
        BB: 18,
        SV: 0,
        HLD: 0,
        BS: 0
      }
    },
    {
      id: "morejon",
      name: "Adrian Morejon",
      position: "P",
      hand: "L/L",
      stats: {
        G: 23,
        GS: 0,
        W: 4,
        ERA: "4.44",
        WHIP: "1.10",
        IP: "26.1",
        K: 32,
        BB: 6,
        SV: 1,
        HLD: 10,
        BS: 4
      }
    },
    {
      id: "miller",
      name: "Mason Miller",
      position: "P",
      hand: "R/R",
      stats: {
        G: 23,
        GS: 0,
        W: 1,
        ERA: "0.76",
        WHIP: "0.80",
        IP: "23.2",
        K: 47,
        BB: 9,
        SV: 16,
        HLD: 0,
        BS: 0
      }
    }
  ],
  nextGames: [
    { date:"FRI MAY 22", time:"6:40 PM PT",  matchup:"SD Padres vs Athletics",           venue:"Petco Park" },
    { date:"SAT MAY 23", time:"6:40 PM PT",  matchup:"SD Padres vs Athletics",           venue:"Petco Park" },
    { date:"SUN MAY 24", time:"1:10 PM PT",  matchup:"SD Padres vs Athletics",           venue:"Petco Park" },
    { date:"MON MAY 25", time:"3:40 PM PT",  matchup:"SD Padres vs Philadelphia Phillies", venue:"Petco Park" },
    { date:"TUE MAY 26", time:"6:40 PM PT",  matchup:"SD Padres vs Philadelphia Phillies", venue:"Petco Park" },
    { date:"WED MAY 27", time:"1:10 PM PT",  matchup:"SD Padres vs Philadelphia Phillies", venue:"Petco Park" },
    { date:"FRI MAY 29", time:"3:45 PM PT",  matchup:"Washington Nationals vs SD Padres",  venue:"Nationals Park" },
    { date:"SAT MAY 30", time:"1:05 PM PT",  matchup:"Washington Nationals vs SD Padres",  venue:"Nationals Park" },
    { date:"SUN MAY 31", time:"10:35 AM PT", matchup:"Washington Nationals vs SD Padres",  venue:"Nationals Park" },
    { date:"TUE JUN 02", time:"3:40 PM PT",  matchup:"Philadelphia Phillies vs SD Padres", venue:"Citizens Bank Park" },
  ],
  seasonHighlights: [
    '<blockquote class="twitter-tweet" data-media-max-width="720"><p lang="und" dir="ltr">Bro 💀 <a href="https://t.co/9AVGorefvr">pic.twitter.com/9AVGorefvr</a></p>&mdash; trev (@BayAreaTrev) <a href="https://twitter.com/BayAreaTrev/status/2054072113351516422?ref_src=twsrc%5Etfw">May 12, 2026</a></blockquote>',
    '<blockquote class="twitter-tweet" data-media-max-width="720"><p lang="en" dir="ltr">Bro was fully ready to lose his life to catch this foul ball <a href="https://t.co/mTXkDlfeGW">pic.twitter.com/mTXkDlfeGW</a></p>&mdash; Dudes Posting Their W’s (@DudespostingWs) <a href="https://twitter.com/DudespostingWs/status/2047029574731551096?ref_src=twsrc%5Etfw">April 22, 2026</a></blockquote>',
    '<blockquote class="twitter-tweet" data-media-max-width="560"><p lang="en" dir="ltr"><a href="https://t.co/d5ydxYnVBn">pic.twitter.com/d5ydxYnVBn</a><br>This fan at the Cubs/Rays game.. didn&#39;t have his best moment trying to get this foul ball.</p>&mdash; The Goal Line Grind (@theGLgrind) <a href="https://twitter.com/theGLgrind/status/2041704519340306733?ref_src=twsrc%5Etfw">April 8, 2026</a></blockquote>',
  ],
  entries: [
    {
      type:"recap", gameLabel:"Game #50", gameDate:"FRI, MAY 22", venue:"PETCO PARK, SAN DIEGO",
      result:"W",
      away:{ abbr:"ATH", city:"ATHLETICS", name:"ATHLETICS" },
      home:{ abbr:"SD",  city:"SAN DIEGO", name:"PADRES"    },
      awayScore:3, homeScore:7, winnerIsHome:true,
      linescore:{
        innings:["1","2","3","4","5","6","7","8","9"],
        away:   ["2","0","0","1","0","0","0","0","0"],
        home:   ["2","0","0","0","1","0","1","3","X"],
        awayTotals:{ R:"3", H:"8", E:"0" },
        homeTotals:{ R:"7", H:"7", E:"0" },
      },
      stats:[
        { label:"WP",        value:"Morejon (1.1 IP, 0 ER, 3 K)", type:"win"     },
        { label:"LP",        value:"J. Springs (6.1 IP, 4 ER)",   type:"loss"    },
        { label:"Machado",   value:"HR, 2 RBI",                   type:"neutral" },
        { label:"Castellanos",value:"HR, 1 RBI",                  type:"neutral" },
        { label:"Laureano",  value:"HR, 1 RBI",                   type:"neutral" },
        { label:"Sheets",    value:"1-4, 2 RBI",                  type:"neutral" },
        { label:"Bogaerts",  value:"0-4, RBI",                    type:"neutral" },
        { label:"Buehler",   value:"5 IP, 5 H, 3 ER, 4 K",       type:"neutral" },
        { label:"Adam",      value:"1 IP, 0 ER",                  type:"neutral" },
      ],
      paragraphs:[
        "Finally, some good fucking food again. The offense was starting to heat up in Seattle and then ran into the mental fucking lock that is the Dodgers, but we might be getting back into business.",
        "Walker Buehler went 5 IP, giving up 3 ER, 4 Ks, not great numbers but I'll take it from mr buehler. His fastball is hitting 95 mph right now, so he might be starting to get his swagger back. That'd be YUGE for this team. Adrian Morejon also has a big peepee because he's just nails when it matters most, and god fearing Jason Adam continues to fear god and be perfect for the Dads in his role. Awesome bullpen. Do we know what we really need according to Mr Preller though? Bullpen help lmfao. How about some starting pitching or some bats instead sir?",
        "The Dads offense continues to shine in the 7th, 8th, 9th innings of games. Just how we drew it up. This game was 3-3 going into the 7th, courtesy of Manny using that humongous, enormous, gigantic ass of his to force a ball out of the park in the 1st inning to score 2 and a big dick nick homer in the 5th to tie the game up. At least we're hitting homers again. Manny's ego is just too fucking large for him to suck ass the whole year so excited to see him get rolling. The nerds also hate Nick Castellanos, don't be a nerd. He'll still get waived eventually but we'll enjoy whatever he provides for the time being and hate exponentially on whenever he sucks. As is the way of fandom.",
        "Once we hit the 7th, it's time for the offense to really come alive. Laureano hits his first homer in forever to make the game 4-3, and then we explode and everyone contributes to score 3 in the bottom of the 8th to make this game 7-3. Just good baseball all around.",
        "A little bit of a bummer, we scored TOO much in the 8th to make this a save situation for Mason, so we do not get to see Mason Miller pitch against his former team quite yet. We'll save that for later apparently. Whatever though, I'll never complain about a dub. Good shit Dads. I also noticed that I spoke a lot about big penises and butts in this report, so stay tuned as to if that's a recurring theme or if this is just a one off.",
      ],
    },
    {
      type:"recap", gameLabel:"Game #49", gameDate:"WED, MAY 20", venue:"PETCO PARK, SAN DIEGO",
      result:"L", seriesResult:"SERIES L 1-2",
      away:{ abbr:"LAD", city:"LOS ANGELES", name:"DODGERS" },
      home:{ abbr:"SD",  city:"SAN DIEGO",   name:"PADRES"  },
      awayScore:4, homeScore:0, winnerIsHome:false,
      linescore:{
        innings:["1","2","3","4","5","6","7","8","9"],
        away:   ["1","0","0","0","0","0","1","2","0"],
        home:   ["0","0","0","0","0","0","0","0","0"],
        awayTotals:{ R:"4", H:"8", E:"0" },
        homeTotals:{ R:"0", H:"5", E:"0" },
      },
      stats:[
        { label:"LP", value:"Padres shut out, drop series 1-2", type:"loss" },
        { label:"Ohtani", value:"Lead-off HR in 1st; dominant on mound", type:"loss" },
        { label:"Tatis Jr.", value:"Bases-loaded, 1-out DP in 5th", type:"loss" },
        { label:"Merrill", value:"Exited after fence collision trying to rob HR", type:"loss" },
      ],
      paragraphs:[
        "Well if yesterday was fun and intense, today was the opposite. In fact, everything that could've gone wrong did go wrong and the vibes were horrendous.",
        "We were going up against Shohei Ohtani pitching today, and he's just a beast pitching the baseball so it was always going to be hard. He's also a beast at hitting the baseball, as he hit a lead off homer in the 1st inning. Jesus Christ, can we please nerf japanese super baseball man. Blizzard please, nerf ASAP.",
        "With that being said, our offense was horrible and it's officially back to Trade Tatis szn. We had our chances in this game, like bases loaded one out in the 5th inning and Tatis coming up to bat. What does this man do? Swing at the first pitch and hit into a double play to end the inning. I'm so over it. This team man.",
        "Oh yeah, Merrill tried to rob Ohtani's lead off homer in the 1st and probably broke a rib jumping up against the fence, so he left this game hurt. What's the point anymore man. Pads lose this game 4-0, and the series 2-1 at home vs the Dodgers. At least we can go back to wearing blue and I don't have to see anymore Dodgers fans invading downtown SD for a bit. Do me a favor and at least check out all THREE of our new season highlights, they're very great and my favorite highlights of the season so far."
      ],
    },
    {
      type:"recap", gameLabel:"Game #48", gameDate:"TUE, MAY 19", venue:"PETCO PARK, SAN DIEGO",
      result:"L",
      away:{ abbr:"LAD", city:"LOS ANGELES", name:"DODGERS" },
      home:{ abbr:"SD",  city:"SAN DIEGO",   name:"PADRES"  },
      awayScore:5, homeScore:4, winnerIsHome:false,
      linescore:{
        innings:["1","2","3","4","5","6","7","8","9"],
        away:   ["2","0","0","0","1","0","1","0","1"],
        home:   ["2","0","0","0","1","1","0","0","0"],
        awayTotals:{ R:"5", H:"9", E:"0" },
        homeTotals:{ R:"4", H:"8", E:"1" },
      },
      stats:[
        { label:"LP", value:"Miller (blown chance after 9th-inning error sequence)", type:"loss" },
        { label:"Canning", value:"5 IP, 3 ER, 5 K", type:"neutral" },
        { label:"Machado", value:"2-run HR in 1st", type:"win" },
        { label:"Andujar", value:"Continues to rake", type:"win" },
        { label:"Morejon + Rodriguez", value:"Big outs out of bullpen", type:"neutral" },
      ],
      paragraphs:[
        "Well this was a very fun, exciting game. And it SUCKS ASS to lose in this fashion.",
        "Griffin Canning starts will always make my butt clench. But he did his job today, going 5 IP, 3 ER given up, and 5 K's. Decent enough vs the Dodgers. Why oh why do we put in Jeremiah Estrada then? he's superman against everyone else but Dodgers are his kryptonite. He didn't do awful, but you can't miss with pitch location against the Dodgers and he gave Freddie Freeman the easiest golf swing into homer ever. Freddie hits a homer off that pitch in his sleep. Just garbage. Adrian Morejon and Bradgley Rodriguez, you are bad ass mother fuckers.  Mason, I'll get to you.",
        "Offense sort of showed up today. We were 4-4 going into the 7th, so I liked our chances. Miggy Andujar continues to be the GOAT, and Manny actually hit a 2 run homer in the 1st after the Dodgers scored 2 in the 1st to tie it up 2-2 (i thought we were in trouble, but the captain comes through here). Unfortunately, we had several opps to score more and we didn't, which is the name of the game and happens sometimes, but it's been happening far too much for my liking. I live with scoring 4 though, that's good enough given the pitching we got today.",
        "Mason Mason Mason. I will not curse you, I really love you actually. But this was a tough way to lose. He gets one out, walks the next batter, and then we ACTUALLY CATCH the base runner trying to steal. Mason goes to through the ball to 1st to kick off the pickle and get a surefire out, except Masons throws a 90 MPH FASTBALL TO THE OUTFIELD. WHAT THE FUCK. Runner goes to 3rd, and all of a sudden, we're in the top of the 9th staring at a base runner on 3rd with 1 out when it could've been no one on and 2 outs. Game LOSING play. Ouch.",
        "I forgive you Mason, but no more of those. He gets his first L of the season, and Tatis was actually up in the bottom of the 9th and had a chance to cement his 1st homer of the season legacy with a what would have been a game tying homer. Instead, he hit a weak ass groundball to 3rd base and we lose. Typical. On to the next one, go win a series vs the Dodgers."
      ],
    },
    {
      type:"recap", gameLabel:"Game #47", gameDate:"MON, MAY 18", venue:"PETCO PARK, SAN DIEGO",
      result:"W",
      away:{ abbr:"LAD", city:"LOS ANGELES", name:"DODGERS" },
      home:{ abbr:"SD",  city:"SAN DIEGO",   name:"PADRES"  },
      awayScore:0, homeScore:1, winnerIsHome:true,
      linescore:{
        innings:["1","2","3","4","5","6","7","8","9"],
        away:   ["0","0","0","0","0","0","0","0","0"],
        home:   ["1","0","0","0","0","0","0","0","X"],
        awayTotals:{ R:"0", H:"5", E:"0" },
        homeTotals:{ R:"1", H:"4", E:"1" },
      },
      stats:[
        { label:"WP",       value:"King (7 IP, 4 H, 0 ER, 9 K)",     type:"win"     },
        { label:"LP",       value:"Yamamoto (7 IP, 3 H, 1 ER, 8 K)", type:"loss"    },
        { label:"SV",       value:"Miller (1 IP, 0 ER, 1 K)",        type:"win"     },
        { label:"Andújar",  value:"HR, 1 RBI — only run of the game", type:"win"    },
        { label:"Adam",     value:"1 IP, 0 ER (8th)",                type:"neutral" },
        { label:"Durán",    value:"CS: Mookie + Ohtani both gunned",  type:"win"    },
        { label:"LAD RISP", value:"0-7",                              type:"win"    },
      ],
      paragraphs:[
        "WELL WELL WELL. Looks like the blue banned plan worked. If I catch any of you wearing blue this week, you will be greeted with a warm fake punch to the gut that leaves you withering in fear. Ask Kyler if you think I'm joking.",
        "DADS WIN in an absolute offensive master class where the final score finishes 1-0. Thank you Miguel Andujar for hitting a solo home run in the 1st, the only score of the entire game. I got a take that's not so hot. Tatis, Merrill, Manny will not be All Stars this year. Mason Miller will for sure be, and I have a pretty strong bet that at least one of Miguel Andujar or Xander Bogaerts will be an all star this year (hopefully Miggy).",
        "In all seriousness, this was a pitcher's duel through and through and exactly the type of baseball that I LOVE watching. Michael King goes 7 IP, 4 hits, 2 walks, and NINE strikeouts. That's what I'm fucking talking about dude. Drive up that value of the signed baseball Laines has. Jason Adam has a sketch as fuck 8th inning, but he perseveres because he's a god fearing man that hates anything that is associated with the color blue. Mason Miller also decides that he feels like fucking around with the Dodgers and walks the first two batters of the inning just to feel something in his private parts as he shuts the door on them.",
        "By the way, Rodolfo Duran has been playing a fair amount of catcher for us while Campy is out, and he's been good. He might not be a MLB level hitter (Fermin might not be either so it's a wash) but he has an absolute cannon of an arm and he threw out both Mookie and Ohtani trying to steal today, that's always a good day behind the plate.",
        "Need our offense to score more runs than 1 (hot take, shocker of a sentence), but always a good start to win the opening game of a home series and even better to beat the Dodgers at home. Vibes:",
      ],
      xPost: '<blockquote class="twitter-tweet" data-media-max-width="560"><p lang="und" dir="ltr">Bro 💀 <a href="https://t.co/9AVGorefvr">pic.twitter.com/9AVGorefvr</a></p>&mdash; trev (@BayAreaTrev) <a href="https://twitter.com/BayAreaTrev/status/2054072113351516422?ref_src=twsrc%5Etfw">May 12, 2026</a></blockquote>',
    },
    {
      type:"recap", gameLabel:"Games #44-46", gameDate:"FRI-SUN, MAY 15-17", venue:"T-MOBILE PARK, SEATTLE",
      result:"W", seriesResult:"SWEEP 3-0",
      away:{ abbr:"SD",  city:"SAN DIEGO", name:"PADRES" },
      home:{ abbr:"SEA", city:"SEATTLE",   name:"MARINERS" },
      awayScore:17, homeScore:7, winnerIsHome:false,
      stats:[
        { label:"Series", value:"Padres sweep Mariners in Seattle", type:"win" },
        { label:"Runs", value:"SD 17 - SEA 7", type:"win" },
        { label:"Hits", value:"Friday: 9, Saturday: 7, Sunday: 10", type:"neutral" },
        { label:"Sheets", value:"3 HR over the final 2 games", type:"win" },
      ],
      seriesGames:[
        {
          gameLabel:"Game #44", gameDate:"FRI, MAY 15", venue:"T-MOBILE PARK, SEATTLE", result:"W",
          away:{ abbr:"SD",  city:"SAN DIEGO", name:"PADRES" },
          home:{ abbr:"SEA", city:"SEATTLE",   name:"MARINERS" },
          awayScore:2, homeScore:0,
          linescore:{
            innings:["1","2","3","4","5","6","7","8","9"],
            away:   ["0","0","0","1","0","0","1","0","0"],
            home:   ["0","0","0","0","0","0","0","0","0"],
            awayTotals:{ R:"2", H:"9", E:"0" },
            homeTotals:{ R:"0", H:"7", E:"1" },
          },
        },
        {
          gameLabel:"Game #45", gameDate:"SAT, MAY 16", venue:"T-MOBILE PARK, SEATTLE", result:"W",
          away:{ abbr:"SD",  city:"SAN DIEGO", name:"PADRES" },
          home:{ abbr:"SEA", city:"SEATTLE",   name:"MARINERS" },
          awayScore:7, homeScore:4,
          linescore:{
            innings:["1","2","3","4","5","6","7","8","9"],
            away:   ["0","1","0","4","0","0","2","0","0"],
            home:   ["0","0","0","1","1","0","0","2","0"],
            awayTotals:{ R:"7", H:"7", E:"0" },
            homeTotals:{ R:"4", H:"8", E:"0" },
          },
        },
        {
          gameLabel:"Game #46", gameDate:"SUN, MAY 17", venue:"T-MOBILE PARK, SEATTLE", result:"W",
          away:{ abbr:"SD",  city:"SAN DIEGO", name:"PADRES" },
          home:{ abbr:"SEA", city:"SEATTLE",   name:"MARINERS" },
          awayScore:8, homeScore:3,
          linescore:{
            innings:["1","2","3","4","5","6","7","8","9"],
            away:   ["1","0","0","0","1","5","1","0","0"],
            home:   ["0","0","0","0","0","3","0","0","0"],
            awayTotals:{ R:"8", H:"10", E:"2" },
            homeTotals:{ R:"3", H:"1", E:"0" },
          },
        },
      ],
      paragraphs:[
        "Welp, sometimes the baseball gods decide to reward us because we had to watch the Padres play ASStastic baseball for a month. We have SWEPT the Seattle Mariners 3-0 in Seattle, and that feels TASTY TASTY.",
        "Starting pitchers did great, bullpen is lockdown (i'm watching you mr matsui), and mason miller loves this team.",
        "Big story is the offense seemed to get going. Padres only scored 2 runs Friday, but got 9 hits, and then scored 7 runs and 8 runs on Saturday and Sunday respectively. That's absolutely massive, and Gavin Sheets is the MVP of this series. 3 HR in the last 2 games, and just absolutely BALLING. He's been on an absolutely tear and i love him to death and will defend him to the grave no matter what happens. Jackson hit some balls hard, Manny is still fat as shit but he's the captain no matter what, and Tatis is still homerless. Some insane aura and good vibes heading into our FIRST, and count it, FIRST series vs the Dodgers so far this season. Bring it the fuck on big blue, see you tomorrow at Petco bitches."
      ],
    },
    {
      type:"recap", gameLabel:"Game #43", gameDate:"THU, MAY 14", venue:"AMERICAN FAMILY FIELD, MILWAUKEE",
      result:"L", seriesResult:"SERIES L 1-2",
      away:{ abbr:"SD",  city:"SAN DIEGO",  name:"PADRES"  },
      home:{ abbr:"MIL", city:"MILWAUKEE",  name:"BREWERS" },
      awayScore:1, homeScore:7, winnerIsHome:true,
      linescore:{
        innings:["1","2","3","4","5","6","7","8","9"],
        away:   ["0","0","0","0","0","0","0","0","1"],
        home:   ["3","3","0","1","0","0","0","0",""],
        awayTotals:{ R:"1", H:"7", E:"2" },
        homeTotals:{ R:"7", H:"10", E:"1" },
      },
      stats:[
        { label:"LP", value:"Canning (1.2 IP, 6 ER)", type:"loss" },
        { label:"Padres bats", value:"1 R, 7 H", type:"neutral" },
        { label:"Bullpen day", value:"Matsui, Marinaccio, Waldron all used", type:"loss" },
      ],
      paragraphs:[
        "Alright, so nothing ever happens. Canning gave up 6 runs in 1.2 IP, so we were fated to lose this game from the jump. Baseball gods are just cruel sometimes, and know that we deserve to watch Griffin Canning, Yuki Matsui, Ron Marinaccio (who i actually like), and Matt Waldron all pitch in the same game. YUCK.",
        "The bats tried (not really, we scored 1 run) by getting 7 hits, but we never had a shot to win this game after the 2nd inning. Moving on, series L and we look to bounce back."
      ],
    },
    {
      type:"recap", gameLabel:"Game #42", gameDate:"WED, MAY 13", venue:"AMERICAN FAMILY FIELD, MILWAUKEE",
      result:"W",
      away:{ abbr:"SD",  city:"SAN DIEGO",  name:"PADRES"  },
      home:{ abbr:"MIL", city:"MILWAUKEE",  name:"BREWERS" },
      awayScore:3, homeScore:1, winnerIsHome:false,
      linescore:{
        innings:["1","2","3","4","5","6","7","8","9"],
        away:   ["0","0","0","0","0","0","0","0","3"],
        home:   ["0","0","0","0","1","0","0","0","0"],
        awayTotals:{ R:"3", H:"6", E:"0" },
        homeTotals:{ R:"1", H:"9", E:"0" },
      },
      stats:[
        { label:"WP",      value:"Jason Adam (1 IP, 0 ER)",           type:"win"     },
        { label:"LP",      value:"Abner Uribe (1 IP, 3 ER, HR)",      type:"loss"    },
        { label:"SV",      value:"Miller (1 IP, 1 H, 0 ER, 2 K)",     type:"win"     },
        { label:"King",    value:"5.2 IP, 6 H, 1 ER, 5 K",           type:"neutral" },
        { label:"Sheets",  value:"3-run HR, 9th inning",              type:"win"     },
        { label:"Andújar", value:"1-4, reach on walk",                type:"neutral" },
        { label:"Bogaerts",value:"4-pitch walk, 9th inning",          type:"neutral" },
        { label:"Tatis Jr.",value:"2-4",                              type:"neutral" },
        { label:"Misiorowski (MIL)", value:"7 IP, 4 H, 0 ER, 10 K",  type:"neutral" },
      ],
      paragraphs:[
        "Welp, the 2026 Padres strike again. If games ended after 7 innings, we might have 5 wins. If the games were only played in the 8th and 9th innings, we might have 35 wins.",
        "Michael King (one of our two capable starters at this point) got the nod today, and went 5.2 IP with 6 hits surrendered but only 1 ER. Honestly, this feels like Michael King's season where his WHIP is high but his ERA is low. There's probably going to be some normalization of this where they're going to meet in the middle throughout the course of the season but I don't care because I love him. Great outing. Bullpen did bullpen things, never an area of concern, they're dominant.",
        "Now the bats were AWFUL today, but alas, that does not matter when you have Gavin Sheets on your team. We headed into the top of the 9th losing 1-0. Good news, Tatis and Manny both immediately got out (though Manny hit the ball far, props), so we had 2 outs in the top of the 9th immediately staring down the barrel of another loss and this one I would've been far more upset about considering Michael King and the bullpen went hard in the mfing paint.",
        "That's when Miggy Andujar got a hit (typical), Xander has a GREAT AB and forces the walk (he didn't know he got walked, it was funny, he stood in the batter's box for like an extra 5 seconds after ball 4 staring at the dugout, goofball), and then GAVIN \"HOLY SHEETS\" SHEETS continues to be just a big booty shot caller. He hits a 3 RUN HR in the top of the 9th and the DADS RALLY AGAIN. Unbelievable stuff.",
        "This is all our reaction, let's keep it going:",
      ],
      xPost: '<blockquote class="twitter-tweet" data-media-max-width="560"><p lang="und" dir="ltr">Bro 💀 <a href="https://t.co/9AVGorefvr">pic.twitter.com/9AVGorefvr</a></p>&mdash; trev (@BayAreaTrev) <a href="https://twitter.com/BayAreaTrev/status/2054072113351516422?ref_src=twsrc%5Etfw">May 12, 2026</a></blockquote>',
    },
    {
      type:"recap", gameLabel:"Game #41", gameDate:"TUE, MAY 12", venue:"AMERICAN FAMILY FIELD, MILWAUKEE",
      result:"L",
      away:{ abbr:"SD",  city:"SAN DIEGO", name:"PADRES"  },
      home:{ abbr:"MIL", city:"MILWAUKEE", name:"BREWERS" },
      awayScore:4, homeScore:6, winnerIsHome:true,
      linescore:{
        innings:["1","2","3","4","5","6","7","8","9"],
        away:   ["0","0","0","2","0","1","0","1","0"],
        home:   ["0","0","1","5","0","0","0","0","X"],
        awayTotals:{ R:"4", H:"8", E:"0" },
        homeTotals:{ R:"6", H:"11", E:"0" },
      },
      stats:[
        { label:"WP",         value:"Sproat (5.1 IP, 6 H, 3 ER, 6 K)",  type:"win"     },
        { label:"LP",         value:"Waldron (2.2 IP, 8 H, 6 ER)",       type:"loss"    },
        { label:"SV",         value:"Uribe",                              type:"win"     },
        { label:"Castellanos",value:"1-4, 2 RBI",                        type:"neutral" },
        { label:"Andújar",    value:"2-4, HR, 2 RBI",                    type:"neutral" },
        { label:"Ortiz (MIL)",value:"HR, 2 RBI",                         type:"neutral" },
        { label:"Frelick (MIL)",value:"2 RBI",                           type:"neutral" },
        { label:"Merrill",    value:"0-5",                                type:"neutral" },
      ],
      paragraphs:[
        "Pads lost 6-4. This honestly was an entertaining game on both sides, and we had a shot at winning, but unfortunately, it's always going to be tough when Matt Waldron gives up 8 hits and 6 earned runs in 2.2 IP. I will say that the 5 run inning the Brewers would've ended sooner if Manny wasn't such a fat ass space case. They bunted to move the runners and he collapsed on the bunt (as he should), but then when it was a bad bunt and it went back to the pitcher, instead of rushing back to third to try to get the out at 3rd, he just pointed at the 1st baseman so Waldron was screwed and had to throw it to 1st and the runner was safe, bases loaded now. In all seriousness, this is a hard play and it's not really Manny's fault, I just like giving him a hard time cause he's the cap.",
        "The bats weren't totally awful today, just a lil awful. We had a shot at more runs but that's just baseball baby. You can be upset about 4 runs but I'm going to choose peace today and say ggs, go next. I've decided that I'm going to stop shit talking Tatis in hopes that he turns it all around because he's capable and is having good at bats, just not happening right now. Merrill is concerning but he's the GOAT so who cares.",
        "GGs, go next!",
      ],
    },
    {
      type:"recap", gameLabel:"Game #40", gameDate:"SUN, MAY 10", venue:"PETCO PARK, SAN DIEGO",
      result:"W", seriesResult:"SERIES T 2-2",
      away:{ abbr:"STL", city:"ST. LOUIS", name:"CARDINALS" },
      home:{ abbr:"SD",  city:"SAN DIEGO", name:"PADRES"    },
      awayScore:2, homeScore:3, winnerIsHome:true,
      linescore:{
        innings:["1","2","3","4","5","6","7","8","9","10"],
        away:   ["0","0","0","2","0","0","0","0","0","0"],
        home:   ["0","0","0","0","0","0","0","0","2","1"],
        awayTotals:{ R:"2", H:"3", E:"0" },
        homeTotals:{ R:"3", H:"4", E:"0" },
      },
      stats:[
        { label:"WP",           value:"Adrian Morejon",                          type:"win"     },
        { label:"LP",           value:"Gordon Graceffo",                         type:"loss"    },
        { label:"Buehler",      value:"6 IP, 3 H, 2 ER, 0 BB",                   type:"neutral" },
        { label:"Estrada",      value:"0.2 IP, 2 K in 10th",                      type:"neutral" },
        { label:"Castellanos",  value:"1-2, 9th-inning game-tying HR",           type:"win"     },
        { label:"Bogaerts",     value:"2-4, 2B, R",                               type:"neutral" },
        { label:"Machado",      value:"Walk-off sac fly (10th)",                 type:"win"     },
        { label:"Padres bats",  value:"4 H, 3 R",                                 type:"neutral" },
      ],
      paragraphs:[
        "THE CARDIAC DADS HAVE STRUCK AGAIN. This game was the standard Padres through 9 innings. Utter ass and totally unwatchable but then MAGIC happened. Ya know what, this might've just been a standard Padres game all around from beginning to end.",
        "The Dads were on pace to have the least amount of hits they've ever had in their franchise history in a 4 game series. Think about that for a second, in the history of the Padres franchise, we were about to set the record for the LEAST amount of hits that the Dads have EVER had in a 4 game series. Against a team that many thought were going to lose 90+ game this year, and the 2nd youngest team in the MLB this year. Like what the actual hell. We have so much money invested in this lineup and underperforming is an understatement.",
        "With that being said, the Cardinals closer is the 2nd best in baseball (behind our very own of course), but the cardiac dads don't care. Let me paint you a picture. It all started with the summer of Xan just getting rolling. Xander Bogaerts gets a single to lead off the inning. Xander's actually probably been our best bat so far this season. Then Ty France and Miggy Andujar just fall over, striking out and not looking competitive at the plate at all (not their fault, the Cardinals closer is a beast). Then, big dick Nick Castellanos steps up to bat. He has an INSANE AB, fouling ball after ball off. On pitch number NINE, he hits a homer and ties this game up at 2-2 and we go to extras. Thank you Nick for doing something for this team before we eventually cut you. Rest easy now, brother. We have the watch, and we will see you in Valhalla.",
        "Walker Buehler had an insane game. Went 6 IP, giving up 3 hits and 2 runs. Great day for a guy that I have an insane amount of mixed feelings about. Bullpen is lights out, and as long as we're competitive with the bats, our pitching can beat anyone if the starter is doing decent.",
        "This game goes to the 10th inning, and the rules are a little different. To speed the game up, the last batter from the last inning starts as a base runner on 2nd base to start the inning. Jeremiah Estrada doesn't care about that, he strikes out two before we give it Morejon to get the last out. We go to the bottom of the 10th. Laureano pitch hit for Fermin, so he goes to 2nd, Jackson gets intentionally walked, Tatis has an awesome AB as well and gets walked so we have bases loaded with no out. Manny swings first pitch of course but gets the sacrifice fly done to score the run and win the game for the dads.",
        "Absolutely insane way to split the series 2-2 here. Everybody make sure to love your moms today, but also be sure to thank the dads for winning for our moms also. Happy dads and moms today (especially the moms)",
      ],
    },
    {
      type:"recap", gameLabel:"Game #39", gameDate:"SAT, MAY 9", venue:"PETCO PARK, SAN DIEGO",
      result:"W",
      away:{ abbr:"STL", city:"ST. LOUIS", name:"CARDINALS" },
      home:{ abbr:"SD",  city:"SAN DIEGO", name:"PADRES"    },
      awayScore:2, homeScore:4, winnerIsHome:true,
      linescore:{
        innings:["1","2","3","4","5","6","7","8","9"],
        away:   ["0","0","0","1","0","0","0","1","0"],
        home:   ["0","0","0","0","3","0","0","1","X"],
        awayTotals:{ R:"2", H:"7", E:"1" },
        homeTotals:{ R:"4", H:"5", E:"0" },
      },
      stats:[
        { label:"WP",          value:"Randy Vásquez (5 IP, 6 H, 1 ER, 6 K)",  type:"win"     },
        { label:"LP",          value:"Dustin May (6 IP, 3 H, 2 ER, 7 K)",      type:"loss"    },
        { label:"SV",          value:"Mason Miller (1.1 IP, 0 H, 0 ER, 4 K)",  type:"neutral" },
        { label:"Morejon",     value:"0.2 IP, 1 H, 1 ER, HBP",                  type:"neutral" },
        { label:"Tatis Jr.",   value:"1-4, 2 RBI",                               type:"neutral" },
        { label:"Machado",     value:"1-4, HR, RBI",                             type:"neutral" },
        { label:"Padres bats", value:"5 H, 2 HR",                                type:"win"     },
      ],
      paragraphs:[
        "WE WON A GAME. I REPEAT, THE PADRES HAVE WON A GAME.",
        "Randy V is just a win farmer, he pitched good not great but somehow just gets the dubski. Only gave up one ER in 5 IP (6 Ks, very nice) and moves to 4-1 on the season. Adrian felt like making this game fun though so he decided to hit a batter and then give up a double just to make it close, it's not a Pads game unless they make your heart beat a little. Good news though, we have Mason Miller and even when he's bad, he's good. He gets the 4 out save, strikes out 4 batters, and also gave the Cardinals a bases loaded situation in the top of the 9th just to feel something.",
        "On an even better note, Fernando got 2 RBIs today on a bloop single and that must've felt good. Whoever wanted to trade him should probably re-evaluate their life and look in the mirror. Manny also decided to hit a homer in the bottom of the 8th just to give us a little wiggle room. In all honesty, we have Mason Miller so it was sort of a useless homerun but I'll take anything I can get from Manny nowadays.",
        "Pads win, we are so back.",
      ],
    },
    {
      type:"recap", gameLabel:"Game #38", gameDate:"FRI, MAY 8", venue:"PETCO PARK, SAN DIEGO",
      result:"L",
      away:{ abbr:"STL", city:"ST. LOUIS", name:"CARDINALS" },
      home:{ abbr:"SD",  city:"SAN DIEGO", name:"PADRES"    },
      awayScore:6, homeScore:0, winnerIsHome:false,
      linescore:{
        innings:["1","2","3","4","5","6","7","8","9"],
        away:   ["0","0","0","0","6","0","0","0","0"],
        home:   ["0","0","0","0","0","0","0","0","0"],
        awayTotals:{ R:"6", H:"11", E:"0" },
        homeTotals:{ R:"0", H:"1",  E:"2" },
      },
      stats:[
        { label:"WP",         value:"Michael McGreevy",                 type:"win"     },
        { label:"LP",         value:"Griffin Canning",                  type:"loss"    },
        { label:"Padres bats",value:"1 hit total",                      type:"loss"    },
        { label:"Top 5th",    value:"Inside-the-park grand slam allowed",type:"loss"    },
        { label:"Canning",    value:"4.2 IP, 6 ER",                     type:"loss"    },
        { label:"RISP",       value:"0-4",                              type:"loss"    },
      ],
      paragraphs:[
        "If yesterday was bad, today was like the worst possible game ever. This game was a rock fight for 3 and a half innings, neither team backing down. Then the wheels officially fell off the wagon.",
        "We had bases loaded in the bottom of the 4th, we don't score a run. That sucks. The Cardinals get the bases loaded in the top of the 5th and hit an inside the park grand slam (the ball DID NOT LEAVE THE BALLPARK, and it was a grand slam). Literally some of the most atrocious baseball I've ever had the opportunity of viewing. Vibes are BAD right now, and our \"superstar\" Tatis is playing not just the worst of his career, but he looks like a player right now that shouldn't be on a major league roster. He's always been a head case, but he always had amazing defense at the very least. He has a single hit at him when the bases are loaded and somehow the ball gets past him and runs back to the wall to blow this game wide open. Trade his ass.",
        "The bats are also cooking something special right now. We got ONE hit this game. ONE. That is right. We almost had a no hitter thrown against us (extremely rare pitching stat) by a guy named Michael McGreevy. That is so fucking Michael McGreasy.",
        "Thank god we beat up on the Giants to hide the fact that the vibes of this team are horrendous and we are actively sucking ass. Trade Tatis and let's reset the team culture/energy.",
      ],
      xPost: "<blockquote class=\"twitter-tweet\" data-media-max-width=\"560\"><p lang=\"en\" dir=\"ltr\">This is the bottom <br><br>Only one way to go<br><br>UP<br><br>Remember this moment<a href=\"https://twitter.com/hashtag/BelieveInTatis?src=hash&amp;ref_src=twsrc%5Etfw\">#BelieveInTatis</a> <a href=\"https://t.co/MDGObk0ZjA\">pic.twitter.com/MDGObk0ZjA</a></p>&mdash; Devine Sports Gospel (@DevineGospel) <a href=\"https://twitter.com/DevineGospel/status/2052950652763193791?ref_src=twsrc%5Etfw\">May 9, 2026</a></blockquote>",
    },
    {
      type:"recap", gameLabel:"Game #37", gameDate:"THU, MAY 7", venue:"PETCO PARK, SAN DIEGO",
      result:"L",
      away:{ abbr:"STL", city:"ST. LOUIS", name:"CARDINALS" },
      home:{ abbr:"SD",  city:"SAN DIEGO", name:"PADRES"    },
      awayScore:2, homeScore:1, winnerIsHome:false,
      linescore:{
        innings:["1","2","3","4","5","6","7","8","9"],
        away:   ["0","0","0","1","0","0","1","0","0"],
        home:   ["1","0","0","0","0","0","0","0","0"],
        awayTotals:{ R:"2", H:"5", E:"0" },
        homeTotals:{ R:"1", H:"4", E:"0" },
      },
      stats:[
        { label:"WP",           value:"Matthew Liberatore",                 type:"win"     },
        { label:"LP",           value:"Bradgley Rodriguez",                  type:"loss"    },
        { label:"SV",           value:"Riley O'Brien",                       type:"neutral" },
        { label:"Michael King", value:"6 IP, 1 ER, 1 H, 6 K",                type:"neutral" },
        { label:"Bogaerts",     value:"RBI in 1st inning",                   type:"neutral" },
        { label:"Padres bats",  value:"No runner reached 2nd after 1st inning", type:"loss" },
      ],
      paragraphs:[
        "This game sucked.",
        "Michael King threw 6 IP, had 6 Ks, and had given up one run (lucky ass homer) and one hit (lucky ass homer). We lost the game 2-1. That's just gross. Horrendous Padres offense.",
        "Xander got the game going with a RBI in the 1st inning, driving home Manny. From then on for the rest of the game, we did not have a base runner get to 2nd base. Just HORRIBLE. This Dads team managed 4 hits overall this game, against a mid ass pitcher. Made that mid ass guy look like a Cy Young award winning ace. Just awful awful awful.",
        "No two ways about it. We are playing bad baseball, and are losing a lot at home. This team somehow started off so hot that we're doing okay, but this team is not long for this world if they continue to play offense like this.",
      ],
    },
    {
      type:"recap", gameLabel:"Game #36", gameDate:"WED, MAY 6", venue:"ORACLE PARK, SAN FRANCISCO",
      result:"W", seriesResult:"SERIES W 2-1",
      away:{ abbr:"SD", city:"SAN DIEGO",     name:"PADRES" },
      home:{ abbr:"SF", city:"SAN FRANCISCO", name:"GIANTS" },
      awayScore:5, homeScore:1, winnerIsHome:false,
      linescore:{
        innings:["1","2","3","4","5","6","7","8","9"],
        away:   ["0","0","0","1","0","0","2","2","0"],
        home:   ["0","0","0","0","1","0","0","0","0"],
        awayTotals:{ R:"5", H:"6", E:"0" },
        homeTotals:{ R:"1", H:"3", E:"1" },
      },
      stats:[
        { label:"WP",        value:"Waldron (5 IP, 2 H, 1 ER, 7 K)", type:"win"     },
        { label:"LP",        value:"Houser (6 IP, 3 H, 2 ER, 3 K)",  type:"loss"    },
        { label:"Morejon",   value:"2 IP, 1 H, 0 ER, 4 K",            type:"neutral" },
        { label:"Miller",    value:"1 IP, 0 H, 0 ER, 2 K",            type:"neutral" },
        { label:"Ty France", value:"PH, 3B, 2 RBI",                   type:"neutral" },
        { label:"Bogaerts",  value:"PH, HR, 2 RBI",                   type:"neutral" },
        { label:"Sheets",    value:"HR",                              type:"neutral" },
        { label:"RISP",      value:"2-10",                            type:"win"     },
      ],
      paragraphs:[
        "well this was a bit of a WACKY one. But the Padres win because we are the best team to ever exist in the history of major league baseball.",
        "this game started out with our reliever Bradgley Rodriguez opening up the game for the Padres before handing the ball over to Waldron in the 2nd inning for him to then pitch 5 IP. I don't really understand why this happens occasionally in modern baseball and what the theory is, as I'm an old head thanks to CB, but whatever, modern MLB. Anyways, Rodriguez gets 3 outs in 7 pitches, and then Waldron has a GREAT run giving up only 2 hits, 1 run (lucky ass home run), and 7 Ks in 5 IP. Morejon comes in and strikes out 4 across 2 IP, and Mason Miller closes it out (not a save situation).",
        "The offense was a little strange in this game, as the lineup mostly performed today but we also scored most of our runs on pinch hitters (we're substituting guys out and subbing guys in to hit). Ty France subbed in and hit a 2 RBI triple, Xander subbed in and hit a 2 RBI HR. Just a wacky, but good day. We win the series vs the Giants 2-1 and I'm still peeved it wasn't a sweep. Vibes are high, just keep winning Dads. All we can ask for.",
      ],
      photo: "https://maxbish.github.io/PadresReport/pictures/xander1_optimized.webp",
      photoFull: true,
    },
    {
      type:"recap", gameLabel:"Game #35", gameDate:"TUE, MAY 5", venue:"ORACLE PARK, SAN FRANCISCO",
      result:"W",
      away:{ abbr:"SD", city:"SAN DIEGO",     name:"PADRES" },
      home:{ abbr:"SF", city:"SAN FRANCISCO", name:"GIANTS" },
      awayScore:10, homeScore:5, winnerIsHome:false,
      linescore:{
        innings:["1","2","3","4","5","6","7","8","9"],
        away:   ["0","1","0","5","1","1","0","2","0"],
        home:   ["2","2","0","0","0","0","1","0","0"],
        awayTotals:{ R:"10", H:"14", E:"0" },
        homeTotals:{ R:"5",  H:"8",  E:"2" },
      },
      stats:[
        { label:"WP",        value:"Buehler (5.1 IP, 7 H, 4 ER, 5 K)", type:"win"     },
        { label:"LP",        value:"Webb (4 IP, 7 H, 6 ER)",            type:"loss"    },
        { label:"Merrill",   value:"3-5, 2B, 2 RBI",                    type:"neutral" },
        { label:"Andújar",   value:"3-5, 2B, 3B, 1 RBI",               type:"neutral" },
        { label:"Bogaerts",  value:"2-5, HR, 2 RBI",                    type:"neutral" },
        { label:"Song",      value:"2-4, 2B, 2 RBI (2nd MLB game)",     type:"neutral" },
        { label:"Castellanos",value:"1-4, 2 RBI",                       type:"neutral" },
        { label:"Estrada",   value:"1.2 IP, 1 HR, 1 ER",               type:"neutral" },
        { label:"RISP",      value:"6-12",                              type:"win"     },
      ],
      paragraphs:[
        "EXPLOSSSIOOONNNN. The offense exploded today, and we can all praise Craig Stammen for continuing to change things up. Merrill hit lead off, Manny hit 2nd, Miguel Andujar hit 3rd, and Fernando Tatis hit 5th. LMAO. Let's fucking go Dads.",
        "Walker Buehler had a decent start today, giving up 7 hits, 4 ER, 5 strikeouts in 5.1 IP. Pretty much a classic day at the office for Mr. Buehler. Neither amazing, but not terrible. We should win with a start like that, and we did thankfully. Relief pitchers did well as well, even though Estrada gave up a homer (rigged).",
        "Remember how I said yesterday that the Padres are boom or bust. Well today, we went BOOM. Scored 10 runs, had 14 hits, and the changes to the lineup order seemed to have done the trick. Funny enough Fernando and Manny did the worst, but just classic at this point. Fernando at least got a hit to keep a 5 run 4th inning going and scored a run. I'm convinced he's never going to hit another homer ever this szn.",
        "We won 10-5, and I wish that we had saved 4 of those runs for tomorrow because we're going to get 4 hits tomorrow total. Let's not talk about that though. Because we have done it. Ladies and gentleman, AJ Preller continues to work his magic. WE HAVE FOUND ANOTHER KOREAN SUPERSTAR, SUNG-MUN SONG. He had 2 hits and 2 RBIs in just his 2nd MLB game and first MLB at bats. He's currently batting .500 and I don't see that going down anytime soon because he's just that good. Stay tuned. Let's hope the explosion continues.",
      ],
      gif: '<div class="tenor-gif-embed" data-postid="20357859" data-share-method="host" data-aspect-ratio="1.77778" data-width="100%"><a href="https://tenor.com/view/megumin-explosion-gif-20357859">Megumin Explosion GIF</a> from <a href="https://tenor.com/search/megumin-gifs">Megumin GIFs</a></div><script type="text/javascript" async src="https://tenor.com/embed.js"><\/script>',
    },
    {
      type:"recap", gameLabel:"Game #34", gameDate:"MON, MAY 4", venue:"ORACLE PARK, SAN FRANCISCO",
      result:"L",
      away:{ abbr:"SD", city:"SAN DIEGO",     name:"PADRES" },
      home:{ abbr:"SF", city:"SAN FRANCISCO", name:"GIANTS" },
      awayScore:2, homeScore:3, winnerIsHome:true,
      linescore:{
        innings:["1","2","3","4","5","6","7","8","9"],
        away:   ["1","0","0","0","0","0","0","0","1"],
        home:   ["2","0","0","0","0","1","0","0","X"],
        awayTotals:{ R:"2", H:"3", E:"0" },
        homeTotals:{ R:"3", H:"6", E:"0" },
      },
      stats:[
        { label:"WP",         value:"T. McDonald (7 IP, 2 H, 1 ER, 8 K)", type:"win"     },
        { label:"LP",         value:"Vásquez (5.2 IP, 5 H, 3 ER)",         type:"loss"    },
        { label:"SV",         value:"Kilian",                               type:"win"     },
        { label:"Merrill",    value:"2-4, HR, RBI",                         type:"neutral" },
        { label:"Laureano",   value:"1-4, HR, RBI",                         type:"neutral" },
        { label:"Devers (SF)",value:"1-4, 2 RBI",                          type:"neutral" },
        { label:"Tatis Jr.",  value:"0-4",                                  type:"neutral" },
        { label:"Machado",    value:"0-4",                                  type:"neutral" },
        { label:"RISP",       value:"0-1",                                  type:"loss"    },
      ],
      paragraphs:[
        "Well I'm extremely frustrated about how this game went today. The Giants rolled out a new pitcher today that they called up from AAA who is literally a combination of Trevor Barton and Ronald McDonald named Trevor McDonald. He is quite literally a back end of rotation starter or solid long inning relief pitcher in the majors. Not a bad pitcher, but not good either. Well he absolutely fucking dominated the Padres today, and I mean DOMINATED. 7 IP innings pitched, 2 hits, 1 ER, 8 strikeouts. Just an elite line by a mid player. This Padres offense is anemic. Wait. What's worse than anemic. That's us.",
        "Randy V had a REALLY decent outing for us today, with the Giants doing a vast majority of their work in the first inning off a 2 run homer. No offense to the starting rotation but we don't have an S-tier starter that's going to shut down the lineup every time they step up to the mound because all of the team's money is tied up in the lineup. That's how this team is constructed. Randy V did great, and the Giants only scored 3 runs today. All the relief guys were great today too, even though I will never like Wandy Peralta and you can't convince me he's good ever so don't even try.",
        "We scored 2 runs today. TWO RUNS, ON THE GIANTS. what the fuck. Do you know what's even worse?? We had 3 HITS TOTAL. THREE. HITS. We scored 2 runs on a solo HR by Jackson and Laureano (one in the 1st inning and one in the 9th inning, now that's the time to score runs, baby). Unbelievably garbage for a team spending the money we are on our bats. The Padres have always been inconsistent at the plate, that's the team that we know and love. They boom and they bust. Unfortunately, they're busting all over place, busting super hard. All over the floor, the walls, the roof, it's just busting everywhere right now. Unbelievably gross. I will root for this team always, but it's a hard watch right now and this was beyond frustrating to watch this game. I never thought I'd say this but I'm open to trading Fernando. Fernando when he's on the Dominican Republic national team looks like an unstoppable force of nature. Fernando when he's on the Padres is the opposite. I love the player, but his head is not right right now and i don't know what it'll take for him to snap out of it, but this team will continue to rack up embarrassing losses like this one tonight unless something changes and changes fast. Thankfully it's a long season and we racked up wins to start the season to put us in a great position for the yoffs, but consequently, the season can become pretty long and pretty pointless pretty fast if you continue to lose games like this one tonight.",
      ],
    },
    {
      type:"recap", gameLabel:"Game #33", gameDate:"SUN, MAY 3", venue:"PETCO PARK, SAN DIEGO",
      result:"W", seriesResult:"SERIES L 1-2",
      away:{ abbr:"CWS", city:"CHICAGO",   name:"WHITE SOX" },
      home:{ abbr:"SD",  city:"SAN DIEGO", name:"PADRES"    },
      awayScore:3, homeScore:4, winnerIsHome:true,
      linescore:{
        innings:["1","2","3","4","5","6","7","8","9"],
        away:   ["0","0","1","0","0","0","2","0","0"],
        home:   ["0","0","0","3","0","0","0","1","X"],
        awayTotals:{ R:"3", H:"7", E:"0" },
        homeTotals:{ R:"4", H:"9", E:"0" },
      },
      stats:[
        { label:"WP",       value:"Adam (1 IP, 0 ER)",           type:"win"     },
        { label:"LP",       value:"T. Davis",                    type:"loss"    },
        { label:"SV",       value:"Miller (1 IP, 0 ER, 3 K)",    type:"win"     },
        { label:"Canning",  value:"5 IP, 3 H, 1 ER, 7 K",       type:"neutral" },
        { label:"Machado",  value:"HR, 1 RBI",                   type:"neutral" },
        { label:"Andújar",  value:"HR, 1 RBI",                   type:"neutral" },
        { label:"Bogaerts", value:"check-swing RBI single, 8th", type:"neutral" },
        { label:"Morejon",  value:"2 IP, 2 ER, HR allowed",      type:"neutral" },
      ],
      paragraphs:[
        "WE FINALLY WON. THE LONG NIGHT IS OVER, OUR WATCH HAS ENDED, ALL THE MEDIA ALLUSIONS.",
        "The Padres saw the same thing as us. The offense was sucking ass and our starting pitching was wavering. So Craig Stammen does as he does and that's shake things up when things aren't going well (he does this even when things are going well but we aren't here to talk about that). The Padres rolled out MLB journeyman and capable starter Griffin Canning for today's game, and boy did that pay off. The journeyman goes 5 IP, 3 hits, 3 walks (BAD, i HATE walks), 7 Ks (GOOD, i LOVE strikeouts), 1 ER on a lucky homer. Booyah baby, now that's a quality start.",
        "The Dads offense kind of showed up today but meh. Miguel Andujar continues to slay, and Manny got going a bit in this game, both hitting solo homers in the same inning. Game was 3-1 going into the 6th.",
        "Adrian Morejon comes in the 6th and does well. He goes in to the 7th and immediately gives up a 2 run homer to make this game exciting at 3-3. If anybody tells you Morejon has been the second coming of Jesus this season, they're wrong. If anybody tells you that Morejon has been disappointing or bad this season, they're just a hater. He's thrown the most of any bullpen arm especially when we lacked depth, and I'm allowing him to show signs of weakness because they are few and far between. After the 2 run homer, Adrian closes out the 7th.",
        "Say what you want about the 2026 Friars, but they have mastered the ability to win games in just absolutely whack ass ways (i included the h for an emphasis in pronunciation). Laureano gets on to start the 8th, Jackson hits a rocket that gets knocked down in the infield but everyone's safe, Manny strikes out (typical), and Xander hits like the BLOOPIEST of BLOOPERS on a check swing to drive a run home. Jackson and Laureano were on 2nd and 3rd respectively, and respectfully, I don't remember how they got there but give me a break. Xander check swings on a 2-2 count but he makes contact with the ball and the ball barely makes it past the mound between the mound and 3rd base. Nobody on the Sox has a play on it, Laureano scores, Xander is safe at first, and that's the ball game because we have Mason Miller.",
        "Mason Miller strikes out two on some nastiness, looked to get back into his groove this game after not being used for a few games. Here comes the winning streak! We lost several games to the Giants to start the season but we're a different ball club and they're definitely a different ball club. Let the games begin, bring it on Giants fans!",
        "Also, Fernando didn't play today LOL. If you haven't seen, I encourage you all to google Fernando Tatis swing because everybody and their mama on the internet has an opinion on his current broken ass swing mechanics and the fact that he's on one of 3 MLB players with 150+ AB and no homers (the other two suck ass, ask Trevor about one of them *cough cough* Luis Arraez *cough cough*).",
      ],
      photo: "https://maxbish.github.io/PadresReport/pictures/xander1_optimized.webp",
      photoFull: true,
      photoCaption: "Another 280 million to Xander Bogaerts. Worth it.",
    },
    {
      type:"recap", gameLabel:"Game #32", gameDate:"SAT, MAY 2", venue:"PETCO PARK, SAN DIEGO",
      result:"L",
      away:{ abbr:"CWS", city:"CHICAGO",   name:"WHITE SOX" },
      home:{ abbr:"SD",  city:"SAN DIEGO", name:"PADRES"    },
      awayScore:4, homeScore:0, winnerIsHome:false,
      linescore:{
        innings:["1","2","3","4","5","6","7","8","9"],
        away:   ["0","0","0","0","0","2","2","0","0"],
        home:   ["0","0","0","0","0","0","0","0","0"],
        awayTotals:{ R:"4", H:"7", E:"0" },
        homeTotals:{ R:"0", H:"6", E:"0" },
      },
      stats:[
        { label:"WP",        value:"Burke (6 IP, 4 H, 0 ER, 8 K)", type:"win"     },
        { label:"LP",        value:"King (6 IP, 7 H, 4 ER, 5 K)",  type:"loss"    },
        { label:"SV",        value:"Domínguez",                     type:"win"     },
        { label:"Estrada",   value:"1 IP, 0 ER, 3 K",              type:"neutral" },
        { label:"Merrill",   value:"2-4",                           type:"neutral" },
        { label:"Andújar",   value:"2-4",                           type:"neutral" },
        { label:"Tatis Jr.", value:"0-4",                           type:"neutral" },
        { label:"RISP",      value:"0-7",                           type:"loss"    },
      ],
      paragraphs:[
        "Full disclosure, I didn't watch a second of the game today. Good news though, you've watched one Padres game you've watched all Padres games. All I need is the box score to be able to tell exactly how this one went (and Pads twitter helps too).",
        "Michael King gets the start in this one, and has a decent start albeit not great by his standards. 7 hits, 4 ER, 5 Ks, 3 walks in 6 IP. Good enough to win in my book. Unfortunately, the Padres have returned from the literal clouds this past road trip and have realized it's difficult to hit a baseball out of the ballpark at sea level. 6 hits total today, and Fernando's getting boo'd at home. Not great vibes, not great vibes at all. Another 0-something (specifically 0-7 today) with runners in scoring position. Another day, another game that's absolutely winnable that we are not winning. Sad days, rough 4 game losing streak. Need the bats to come alive, but specifically we need Fernando, Jackson (who had 2 hits today), and Manny to really come alive at some point for us to keep pace with the Dodgers.",
        "On a brighter note, Jeremiah Estrada is back and he provides much needed bullpen depth. We love to see that, and he strikes out the only 3 batters that he sees today. Very encouraging. Also, the good news about our losing streak is that the entire division has all decided to stand in solidarity with our complete buttcheeks-ness and lose all their games too. Dodgers have lost 4 in a row too, and we're still just a half game back from the division lead. Things could be worse. The only team in the MLB on a worse losing streak than the Dodgers and Padres right now is Trevor's very own San Francisco Giants, who have lost 5 in a row. Good news everyone, the Padres play the Giants next after this series in SF. Shoutout Trevor! We could use a few dubskis. Good night everyone, and I'll see you on church day tomorrow.",
      ],
    },
    {
      type:"recap", gameLabel:"Game #31", gameDate:"FRI, MAY 1", venue:"PETCO PARK, SAN DIEGO",
      result:"L",
      away:{ abbr:"CWS", city:"CHICAGO",   name:"WHITE SOX" },
      home:{ abbr:"SD",  city:"SAN DIEGO", name:"PADRES"    },
      awayScore:8, homeScore:2, winnerIsHome:false,
      linescore:{
        innings:["1","2","3","4","5","6","7","8","9"],
        away:   ["0","6","0","0","1","0","0","1","0"],
        home:   ["0","0","0","0","0","0","0","2","0"],
        awayTotals:{ R:"8", H:"8", E:"0" },
        homeTotals:{ R:"2", H:"6", E:"0" },
      },
      stats:[
        { label:"WP",               value:"Schultz (6 IP, 2 H, 0 ER, 2 K)",  type:"win"     },
        { label:"LP",               value:"Márquez (5 IP, 5 H, 7 ER, 5 BB)", type:"loss"    },
        { label:"Tatis Jr.",        value:"3-4, 3B",                           type:"neutral" },
        { label:"Murakami (CWS)",   value:"HR, 3 RBI",                         type:"neutral" },
        { label:"Montgomery (CWS)", value:"HR, 1 RBI",                         type:"neutral" },
        { label:"Marinaccio",       value:"2 IP, 1 ER",                        type:"neutral" },
        { label:"Peralta",          value:"2 IP, 0 ER",                        type:"neutral" },
      ],
      paragraphs:[
        "The German Meatball got the start tonight and immediately went to work, giving up 6 runs in the 2nd inning via 3 hits and 4 walks. The walks have been a REALLY big problem as of late for every starter. We cannot continue to allow free base runners to the opposing teams, it's just awful awful ball.",
        "Noah Schultz got the start tonight for the Southside Sox. He is a fucking beast. 22 years old, rookie, and looking like he has got the stuff to be an ace in this league for a long time. We only managed 2 hits in 6 IP against this guy. I wish we had a pitcher like this guy. Also, the Sox have a guy named Munetaka Murakami whose nickname is the Southside Samurai, which is objectively a baddddd asssss nickname. He's a Japanese 1st baseman and he's tied for the league lead in homers (he hit a 3 run homer tonight off the meatball thrower). He's on pace for 66 HRs this year. Southside Samurai indeed. Sox are building something nicely.",
        "Jackson got a rest day, Tatis showed up and went 3-3, nobody else did jack. Just a classic Pads storyline for this season during this 3 game losing streak. Good thing we'll turn it around tomorrow!",
      ],
    },
    {
      type:"recap", gameLabel:"Game #30", gameDate:"WED, APRIL 30", venue:"PETCO PARK, SAN DIEGO",
      result:"L",
      away:{ abbr:"CHC", city:"CHICAGO",   name:"CUBS"   },
      home:{ abbr:"SD",  city:"SAN DIEGO", name:"PADRES" },
      awayScore:5, homeScore:4, winnerIsHome:false,
      linescore:{
        innings:["1","2","3","4","5","6","7","8","9"],
        away:   ["0","1","0","2","0","1","0","1","0"],
        home:   ["0","0","0","0","3","0","0","1","0"],
        awayTotals:{ R:"5", H:"9", E:"0" },
        homeTotals:{ R:"4", H:"3", E:"0" },
      },
      stats:[
        { label:"WP",                   value:"Taillon (7 IP, 3 H, 3 ER, 6 K)", type:"win"     },
        { label:"LP",                   value:"Morejon",                         type:"loss"    },
        { label:"SV",                   value:"Milner",                          type:"win"     },
        { label:"Waldron",              value:"5 IP, 6 H, 3 ER",                type:"neutral" },
        { label:"Castellanos",          value:"HR, 2 RBI",                       type:"neutral" },
        { label:"Andújar",              value:"HR, 1 RBI",                       type:"neutral" },
        { label:"Crow-Armstrong (CHC)", value:"HR, 3 RBI",                       type:"neutral" },
        { label:"Adam",                 value:"1 IP, 1 HR, 1 ER",               type:"neutral" },
      ],
      paragraphs:[
        "Now this one hurt. We had all the chances in the world to win this game and we didn't. Just bad baseball. Padres got 0-3 with RISP, we have bases loaded with no outs in the 8th and score 1 run. That's just awful.",
        "Waldron, similar to Buehler, has neither a good nor bad start. That's okay, that's what we expect. What we cannot have is Manny, Tatis, and Jackson going 1-10 in this game. What's been underrated behind Tatis' extremely slow start to the year is that Jackson has been probably even worse so far. Tatis' underlying metrics indicate he's going to start raking soon, but Jackson's are just flat out bad. Not ideal.",
        "We have every chance to win this game, the Cubbies starter goes absolutely insane and goes 7 IP and only gives up 3 hits, and we still could've won. This team is good and they fight. Just a tough series to lose at home and we NEED the stars to start playing like stars ASAP or this will not be good. Good news though, we got a meh White Sox team coming to town. Let's stack some Ws boys.",
      ],
    },
    {
      type:"recap", gameLabel:"Game #29", gameDate:"TUE, APRIL 29", venue:"PETCO PARK, SAN DIEGO",
      result:"L",
      away:{ abbr:"CHC", city:"CHICAGO",   name:"CUBS"   },
      home:{ abbr:"SD",  city:"SAN DIEGO", name:"PADRES" },
      awayScore:8, homeScore:3, winnerIsHome:false,
      linescore:{
        innings:["1","2","3","4","5","6","7","8","9"],
        away:   ["0","2","0","0","0","2","4","0","0"],
        home:   ["0","1","0","1","0","1","0","0","0"],
        awayTotals:{ R:"8", H:"8", E:"0" },
        homeTotals:{ R:"3", H:"6", E:"1" },
      },
      stats:[
        { label:"WP",                   value:"Cabrera (5.2 IP, 6 H, 3 ER, 7 K)", type:"win"     },
        { label:"LP",                   value:"Kyle Hart",                          type:"loss"    },
        { label:"Buehler",              value:"4.2 IP, 3 H, 2 ER, 4 K",           type:"neutral" },
        { label:"Bogaerts",             value:"HR, 1 RBI",                         type:"neutral" },
        { label:"Crow-Armstrong (CHC)", value:"HR, 3 RBI",                         type:"neutral" },
        { label:"Tatis Jr.",            value:"0-4",                               type:"neutral" },
        { label:"Merrill",              value:"0-4",                               type:"neutral" },
      ],
      paragraphs:[
        "So this game is closer than the box score shows. This game was tied 3-3 going into the 6th, and was 4-3 Cubbies going into the 8th. Anyone's game still. Unfortunately, we gave up a 3 HR to Pete Crow Armstrong who either has the best name ever or the worst name ever. He also looks like a white nationalist but who are we to judge.",
        "The fact of the matter is that Walker Buehler didn't have a bad nor good start, and our stars are continuing to not show up. Manny had the day off, and Fernando and Jackson went 0-8 combined. We aren't going to win a lot of games if Walker Buehler only goes 4.2 IP and our boys can't score runs. Competitive game, but not enough vs a good team here.",
      ],
    },
    {
      type:"recap", gameLabel:"Game #28", gameDate:"MON, APRIL 28", venue:"PETCO PARK, SAN DIEGO",
      result:"W",
      away:{ abbr:"CHC", city:"CHICAGO",   name:"CUBS"   },
      home:{ abbr:"SD",  city:"SAN DIEGO", name:"PADRES" },
      awayScore:7, homeScore:9, winnerIsHome:true,
      linescore:{
        innings:["1","2","3","4","5","6","7","8","9"],
        away:   ["0","1","4","0","0","0","0","0","2"],
        home:   ["3","0","1","0","2","0","2","1","X"],
        awayTotals:{ R:"7", H:"8",  E:"0" },
        homeTotals:{ R:"9", H:"14", E:"0" },
      },
      stats:[
        { label:"WP",       value:"Vásquez (5 IP, 5 ER, 4 K)",  type:"win"     },
        { label:"LP",       value:"Ben Brown",                   type:"loss"    },
        { label:"Ty France",value:"2-5, 2B, 3B, 4 RBI",         type:"neutral" },
        { label:"Machado",  value:"3-4, 2 2B, 3 R",             type:"neutral" },
        { label:"Sheets",   value:"HR (2 out, 2 strike, 8th)",  type:"neutral" },
        { label:"Morejon",  value:"1.2 IP, 0 ER, 2 K",          type:"neutral" },
        { label:"Adam",     value:"1.1 IP, 0 ER, 1 K",          type:"neutral" },
        { label:"Miller",   value:"1 IP, 2 ER (streak ends)",    type:"neutral" },
      ],
      paragraphs:[
        "So let start off by saying that Laines and I went to this game and it was ELECTRIC. The vibes started off so high with a 3 run 1st inning. Ty France was 5 feet short of hitting a grand slam, but we'll settle for a 2 RBI double.",
        "Randy V had a pretty rough outing, giving up 5 runs thru 5 IP, but he still gets the W in this one. The defense was also shaky in this game, but it didn't matter because we scored 9 runs in this game. Manny is starting to get hot too, he hit 2 doubles in this game before leaving for precautionary reasons. The precautionary reason is he is so fat that sliding into second twice hurt his hamstrings. Laines even made a comment watching the replay on the big screen that he had that pufferfish, teeth clenched look in the face while sprinting as fast as he could to 2nd (he wasnt moving that fast, he was trying his best tho, really hope he's all healthy and set for tomorrow.)",
        "MVP of the game on offense was Ty France. He had a double, a triple, and 4 RBI in this game. Best cheap bat of the season so far and it's not even close. He's an above average defender with the glove too so we are cooking with gas with this fella.",
        "Adrian Morejon came in in the 6th and shut em down for 1.2 IP, Jason Adam came in and shut em down for 1.1 IP, and then the story of this game came.",
        "Mason Miller comes in because he was the only one warmed up considering the game was 8-5 with 2 outs in the 8th. Then Gavin Sheets who came in for Manny hit a homer with 2 strikes 2 outs in the bottom of the 8th. Hence making the game 9-5. Xander gets out immediately after, and nobody else is warmed up in the bullpen so we have to put Mason Miller in in a non-save situation. Not ideal. The vibes were off, and they didn't even do his sick ass entrance because we all didn't even realize he was coming in in a non-save situation. Then his very first batter, the umpire makes one of the worst calls you'll see this entire baseball season. See the below image.",
        "That is the baseball on the foul side of the line before it gets picked up. The umpire called that ball fair, and it's not reviewable so the leadoff runner was on. The call was so horrific it threw off Miller, eventually leading to him giving up 2 runs and ending his record setting scoreless streak. Just absolutely disgusting. Don't worry though, we all did our job in Petco and boo'd the umpire for the entirety of the next 3 at bats (which probably didn't help Miller either.) Anyways, he got the final 3 outs and doesn't get a save but we win so whatever. Dads 9-7, we focus on that and aim at getting a series W by winning tomorrow. Dads have won a few in a row at home, let's keep that going!",
      ],
      photo: "https://maxbish.github.io/PadresReport/pictures/horriblecall.webp",
      photoCaption: "That ball is foul. Not reviewable. Criminal.",
    },
    {
      type:"recap", gameLabel:"Game #27", gameDate:"SUN, APRIL 27", venue:"MEXICO CITY, MEXICO",
      result:"L",
      away:{ abbr:"SD", city:"SAN DIEGO", name:"PADRES"       },
      home:{ abbr:"AZ", city:"ARIZONA",   name:"DIAMONDBACKS"  },
      awayScore:7, homeScore:12, winnerIsHome:true,
      linescore:{
        innings:["1","2","3","4","5","6","7","8","9"],
        away:   ["0","1","2","0","3","1","0","0","0"],
        home:   ["0","0","0","0","1","1","6","4","X"],
        awayTotals:{ R:"7",  H:"11", E:"0" },
        homeTotals:{ R:"12", H:"15", E:"1" },
      },
      stats:[
        { label:"WP",          value:"Thompson",              type:"win"     },
        { label:"LP",          value:"B. Rodriguez",          type:"loss"    },
        { label:"King",        value:"6 IP, 3 H, 2 ER, 8 K", type:"neutral" },
        { label:"Machado",     value:"2 HR, 5 RBI",           type:"neutral" },
        { label:"Campusano",   value:"2-4, HR, 2B, 2 RBI",   type:"neutral" },
        { label:"Marinaccio",  value:"0.1 IP, 5 H, 4 ER",    type:"loss"    },
        { label:"D. Morgan",   value:"0.1 IP, 4 H, 4 ER",    type:"loss"    },
        { label:"Vargas (AZ)", value:"3-5, GS, 4 RBI",       type:"neutral" },
      ],
      paragraphs:[
        "Well that was an incredibly strange and shitty game today.",
        "The Dads just straight up dominated for 6 innings today. Michael King dominated, Manny Machado took advantage of some high elevation, and Luis Campusano had another day worth talking about.",
        "Michael King gave up 3 hits (2 being home runs, thanks Mexico City) thru 6 IP and struck out 8. Pretty sure there was a point in this game where he had struck out 7 of the previous 8 batters. Just an elite day from our guy. Control looks shaky at times but if he stays healthy, he'll be a force for us all year long.",
        "Meanwhile, Manny heard me making fun of him for being fat and decided to use that fat ass to smash two balls out of the park. 2 HR, 5 RBI day for Manny, sheesh. Campy also hit a HR and had 2 RBI today, one coming on a double and the other the HR. He's no longer just dominating AAA, he's been straight up dominating MLB pitchers and thats a GREAT sign for this ballclub.",
        "Dads lead 7-2 heading into the bottom of the 7th..",
        "Unfortunately, that worry that I mentioned previously about our bullpen came to rear its ugly, disgusting, repulsive head today. Morejon and Adam didn't pitch, and as a result, the Padres bullpen gave up 10 runs and 12 hits in the 7th and 8th inning combined. This game went from cruise control for the Dads, to a holy fucking shit, we're losing 12-7 in a real heartbeat. I don't think we'll see another outing like this one from our bullpen, the DBacks also took insane advantage of Mexico City literally being heaven for batters (and it might literally be heaven in general because of the altitude.) They had a guy hit his first career grand slam today and I guarantee that ball is not leaving the ballpark in Petco or Arizona.",
        "Shit happens, sometimes you fluke and sometimes you get fluked. We let it go, split the season series, and focus up on a BIG series vs another good team in the Cubbies at home.",
        "See you all tomorrow. Mara or Kyler, if you're reading this, text me your favorite color ASAP or else I'm going to complain that you aren't reading my daddies report. 😭",
      ],
    },
    {
      type:"recap", gameLabel:"Game #26", gameDate:"SAT, APRIL 26", venue:"MEXICO CITY, MEXICO",
      result:"W", seriesResult:"W",
      away:{ abbr:"SD", city:"SAN DIEGO", name:"PADRES"      },
      home:{ abbr:"AZ", city:"ARIZONA",   name:"DIAMONDBACKS" },
      awayScore:6, homeScore:4, winnerIsHome:false,
      linescore:{
        innings:["1","2","3","4","5","6","7","8","9"],
        away:   ["0","0","0","0","1","0","4","0","1"],
        home:   ["0","4","0","0","0","0","0","0","0"],
        awayTotals:{ R:"6", H:"6", E:"1" },
        homeTotals:{ R:"4", H:"7", E:"3" },
      },
      stats:[
        { label:"WP",        value:"Márquez (6 IP, 4 ER)",      type:"win"     },
        { label:"LP",        value:"Clarke",                     type:"loss"    },
        { label:"SV",        value:"Miller (13 P, 1 IP, 0 ER)", type:"win"     },
        { label:"Ty France", value:"2-4, 2 HR, 2 RBI",          type:"neutral" },
        { label:"Sheets",    value:"2 RBI single",               type:"neutral" },
        { label:"Waldron",   value:"5 IP, 6 ER",                 type:"neutral" },
      ],
      paragraphs:[
        "Life comes at you fast. It comes at you even faster if the German Meatball is pitching in Mexico City. He threw 5 outs, decided he was pitching TOO well, and it was time to get some meatballs involved. He then gave up 4 consecutive runs with 2 outs in the 2nd. Thankfully mr meatball locked in and didnt give up another run in his outing thru 6 innings. Mr Meatball in all honesty has been pitching like so much better than what we were all expecting out of him this season. Morejon got the nod in the 7th and did his thing (his thing includes two runners getting on base but also striking out two batters, i love him so much). Jason Adam got the nod in the 8th. He continues to have little control over his fastball but every other pitch is elite. Mason Miller came in for the 9th to close this game out and did just that. He sets the franchise record for most consecutive innings pitched without giving up a score. MVP. If our starting pitching can get through 6 innings consistently, the Morejon Adam Miller ending rotation is so incredibly dominant.",
        "Fortunately, life comes at you the fastest if you're the Diamondbacks playing in Mexico City. Their starting pitcher got hit by a ball after Fermin hit the ball back at him and railed him in his throwing shoulder. He had to leave the game. Their starting shortstop also rolled his ankle and got actually hurt in the 7th (in honor of the NFL draft, I thought he had torn his Achilles at first.) He had to leave the game. And best of all, all the fans in Mexico City fucking hate the DBacks and love the Padres. Say what you want, but Mexico City people and I would all be best friends considering we love the Niners and the Padres.",
        "This Padres offense is hilarious. They do absolutely nothing for 7-8 innings a game but then blow up out of nowhere to score enough runs to win the game all in 1-2 innings. We had the bases loaded TWICE with no outs in just the 7th inning alone, and Gavin Sheets continues to be a baller shot caller (2 RBI single in the 7th). 4 run 7th inning no big deal. Fun fact, Jackson Merrill got to bat twice in the 7th (he started the inning with a walk and then ended the inning as the last out.) Ty France also homered twice this game lmao. Elevation diff.",
        "All in all, this was one of the games played in Mexico City of all time. Fun Fact x2: Mexico City is 7,300+ ft above sea level (clears Denver by 1,800+ ft). If Fernando cant hit a home run tomorrow, we might as well just accept he's never going to hit another homer ever again. The Dads do be out here getting their conditioning in at this high elevation, which I love but is also Manny's personal hell. Do you know what Manny and I both love though? A Padres victory, 6-4. A great victory against a team that we'll be competing with for a postseason spot, let's get another one tomorrow.",
      ],
    },
    {
      type:"recap", gameLabel:"Game #25", gameDate:"THU, APRIL 24", venue:"COORS FIELD, DENVER",
      result:"W", seriesResult:"SERIES W 2-1",
      away:{ abbr:"SD",  city:"SAN DIEGO", name:"PADRES"  },
      home:{ abbr:"COL", city:"COLORADO",  name:"ROCKIES" },
      awayScore:10, homeScore:8, winnerIsHome:false,
      linescore:{
        innings:["1","2","3","4","5","6","7","8","9"],
        away:   ["0","0","0","2","0","2","0","1","5"],
        home:   ["0","3","0","0","3","0","2","0","0"],
        awayTotals:{ R:"10", H:"12", E:"0" },
        homeTotals:{ R:"8",  H:"11", E:"0" },
      },
      stats:[
        { label:"WP",       value:"Marinaccio",                type:"win"     },
        { label:"SV",       value:"Miller",                    type:"win"     },
        { label:"LP",       value:"Vodnik",                    type:"loss"    },
        { label:"Sheets",   value:"3-run HR, go-ahead in 9th", type:"neutral" },
        { label:"Andújar",  value:"2 RBI, key singles",        type:"neutral" },
        { label:"Bogaerts", value:"multi-hit",                 type:"neutral" },
        { label:"Waldron",  value:"5 IP, 6 ER",                type:"neutral" },
      ],
      paragraphs:[
        "HOLY SHEETS. What a game. If you are an absolute loser and a mindless, employed sheep of society, you probably didnt catch this game (I couldnt watch either). And boy oh boy, did we miss out.",
        "Let's start with the bad. I made a comment about our starting pitching being elite to start the season at the beginning of this series. That turned out to be just a wittle bit of a lie. Turns out that Matt Waldron should probably go back to just trying to throw a knuckleball 90% of the time and hope it doesn't get smashed. Waldron went 5 innings and gave up more runs than innings pitched, but we're not here to talk about that.",
        "This game was 8-4 going into the 8th in favor of the Rockies and things felt worse. The Rockies were racking, Morejon gave up a homer (Rockies are cheating, it's obvious), and while we had scored some runs, the bats were just not showing up. Merrill up to that point had 3 strikeouts on 3 plate appearances just to share the feeling of how this one was going.",
        "However, this team has some mother freaking fight in them. We score a run in the 8th. Tatis even had a chance at hitting a 3 run HR in the 8th to tie this game up, but nah, strikeout for Tatis. That doesn't matter tho (it actually does and I'll expand on that later). Ron Marinaccio shuts down the Rockies in the bottom of the 8th.",
        "Then all hell breaks loose. Jackson Merrill decides he's tired of striking out today and gets a lead off walk. Manny singles. The summer of Xan continues and he singles (driving in Jackson). Miguel Andujar and Xander legit carried this team offensively today, and Miggy singles to score Manny. And then, the birthday boy arrives. Gavin mfing Sheets walks up there, and on the first pitch screams \"I fucking HATE losing\" and he rips a ball down the right field line and it is GONE. 3 RUN HOMER to take a 10-8 lead. At that point, the game might as well end because we have Mason Miller.",
        "Mason Miller comes in for the save attempt, gives up 1 hit strangely enough to the second batter, but ends up throwing 7 total pitches to get 3 outs in the bottom of the 9th to close this game and series out. Padres win 10-8, Mason Miller gets the save (didn't throw a strikeout so he's not winning the Cy Young award anymore sadly), and the Dads win the series on the road 2-1.",
        "As insane of a victory as I can remember for this season so far. So I want to take this time to send a message to our friend Fernando. Whenever you feel like being a professional hitter again for this Padres team, that'd be really dope because we're basically unbeatable when you get your swagger back.",
        "Up next: Short 2 game series vs the DBacks in Zona and we need wins against this team, both division wise and wild card race wise. Let's go Dads!",
      ],
    },
    {
      type:"recap", gameLabel:"Game #24", gameDate:"WED, APRIL 22", venue:"COORS FIELD, DENVER",
      result:"L",
      away:{ abbr:"SD",  city:"SAN DIEGO", name:"PADRES"  },
      home:{ abbr:"COL", city:"COLORADO",  name:"ROCKIES" },
      awayScore:3, homeScore:8, winnerIsHome:true,
      linescore:{
        innings:["1","2","3","4","5","6","7","8","9"],
        away:   ["1","0","0","0","0","0","1","0","1"],
        home:   ["0","4","0","1","0","1","1","1","—"],
        awayTotals:{ R:"3", H:"7",  E:"0" },
        homeTotals:{ R:"8", H:"15", E:"1" },
      },
      stats:[
        { label:"WP",          value:"Sugano",                          type:"win"     },
        { label:"LP",          value:"W. Buehler (2.2 IP, 8 H, 4 ER)", type:"loss"    },
        { label:"Campusano",   value:"3-4, HR, 2 2B, RBI",              type:"neutral" },
        { label:"Bogaerts",    value:"2-4",                             type:"neutral" },
        { label:"Merrill",     value:"RBI",                             type:"neutral" },
        { label:"Buehler ERA", value:"13.50",                           type:"neutral" },
      ],
      paragraphs:[
        "We witnessed a miracle today. This must've been what it felt like when we landed on the moon, when we discovered the cure to polio, etc etc. The Padres scored a run in the 1st inning! Of course it was due to The Magnificent Merrill and his beautiful textbook single to drive in Laureano.",
        "However, this euphoric feeling did not last because washed ass Walker Buehler summoned his Dodgers DNA and got lit the fuck up for 4 runs in the 2nd inning. A little fishy if you ask me. He got pulled after 3 innings. It was a rough game, bullpen got used a lot.",
        "Unfortunately, overcoming a 4-1 deficit is just not in this team's DNA currently. We scored 2 more but not before they added 4 more runs to their total. Dads lose, but that's okay. Cant win em all.",
      ],
    },
    {
      type:"recap", gameLabel:"Game #23", gameDate:"TUE, APRIL 21", venue:"COORS FIELD, DENVER",
      result:"W",
      away:{ abbr:"SD",  city:"SAN DIEGO", name:"PADRES"  },
      home:{ abbr:"COL", city:"COLORADO",  name:"ROCKIES" },
      awayScore:1, homeScore:0, winnerIsHome:false,
      linescore:{
        innings:["1","2","3","4","5","6","7","8","9"],
        away:   ["0","0","0","0","0","1","0","0","0"],
        home:   ["0","0","0","0","0","0","0","0","0"],
        awayTotals:{ R:"1", H:"6", E:"0" },
        homeTotals:{ R:"0", H:"3", E:"1" },
      },
      stats:[
        { label:"WP",           value:"Vásquez (7 IP, 3 H, 0 ER, 5 K)", type:"win"     },
        { label:"SV",           value:"Morején (2 K)",                   type:"win"     },
        { label:"Machado",      value:"walk-off RBI walk, bases loaded",  type:"neutral" },
        { label:"Tatis Jr.",    value:"2-4",                             type:"neutral" },
        { label:"COL Ks",       value:"15",                              type:"neutral" },
        { label:"Dollander LP", value:"9 K, 6 IP, 1 ER",                type:"loss"    },
      ],
      paragraphs:[
        "An unstoppable force meets an extremely movable object. The Padres offense continues to roll, as they mustered ONE whole run in this game. The Rockies stadium is well known to lend itself to some insanely high scoring games due to its smaller size and the high elevation in Colorado (the ball goes farther, it just does). You'll be shocked to hear then that the Rockies pitchers threw 15 strikeouts. Maybe they were cheating and drilled holes in the Dads' bats, more to come on this theory as the series continues.",
        "Good news tho, the Rockies cant cheat their way around the rules. They fell for the ultimate Dads trap. Bases loaded, full 3-2 count, 2 outs, Manny Machado up to bat, and the Rockies feel his immense fat ass aura and walk him, hence also walking in the only run of the day. DOMINATING OFFENSE.",
        "Randy Vasquez continues to start the season extremely strong, and is probably our #1 right now. He goes 7 IP, only giving up 3 hits. Our starting pitching is elite, which is actually the most insane thing about the start of this season so far.",
        "We decided we didnt need Mason Miller to close this game, so Adrian Morejon came in, struck out two immediately, and then almost gave up a home run but it was caught by our lord and savior Jackson Merrill well short of the fence. Padres dominate the Rockies 1-0. All we do is win, win, win.",
      ],
    },
    {
      type:"offday", gameLabel:"Off Day", offDaySub:"BEFORE THE COLORADO SERIES", result:"OFF",
      paragraphs:[
        "We did not play a game today, therefore we are just a 0.5 game back of the Dodgers as I type this.",
        "However, the Dodgers do play today and are beating the Rockies currently so standings subject to change. The Dodgers also baselessly accused the Rockies of cheating this past weekend, because it is absolutely ridiculous to think that a team can win their own home stadium against a 1 billion dollar roster. With that being said, the Padres are kicking off their series against the Rockies in Colorado tomorrow so stand up and stand by in case we jump onto the bandwagon and also accuse them of cheating.",
      ],
    },
    {
      type:"recap", gameLabel:"Game #22", gameDate:"SUN, APRIL 19", venue:"ANGEL STADIUM, ANAHEIM",
      result:"W", seriesResult:"SERIES W 2-1",
      away:{ abbr:"SD",  city:"SAN DIEGO",   name:"PADRES" },
      home:{ abbr:"LAA", city:"LOS ANGELES", name:"ANGELS" },
      awayScore:2, homeScore:1, winnerIsHome:false,
      linescore:null, stats:[],
      paragraphs:[
        "The Dads' offense continues to an unstoppable force of nature, putting up 2 whole runs in this game. When you get contributions from Bryce Johnson at the plate, feels like a victory is all but guaranteed.",
        "Michael King continues to be very good. That signed ball by Mr King that Laines won during opening weekend is just gaining more and more value, so we will continue to trust our ace every time he takes the mound. I wonder if we'll be able to exchange that ball for some raw, beautiful, malleable gold.",
        "Something that is not being talked about is that anybody not named Adrian Morejon or Mason Miller scares the ever living shit out of me when they go to the bullpen. Jason Adam will figure it out because he's a god fearing conservative white man, but everybody else makes me nervous right now.",
        "Mason Miller is the GOAT. The Dads win 2-1 and win the series 2-1. Happy church day and to all a good nap.",
      ],
    },
    {
      type:"recap", gameLabel:"Game #21", gameDate:"SAT, APRIL 18", venue:"ANGEL STADIUM, ANAHEIM",
      result:"W", seriesResult:"W 4-1",
      away:{ abbr:"SD",  city:"SAN DIEGO",   name:"PADRES"  },
      home:{ abbr:"LAA", city:"LOS ANGELES", name:"ANGELS"  },
      awayScore:4, homeScore:1, winnerIsHome:false,
      linescore:null, stats:[],
      paragraphs:[
        "Our starting pitcher was German Marquez, who I call the German Meatball. He is not German, but he does throw meatballs. Thankfully, no balls left the park vs him today as he went 5 and 2/3 IPs allowing only 2 hits.",
        "While the german meatball was out there proving that the Angels are in fact ass, we are also ass because this game was 0-0 going into the 8th inning. Thankfully, we scored 2 runs on two of the softest hits that I have ever seen and its better to be lucky than good. We added on to our lead in the 9th the same exact way, but at least Tatis drove some runs home (he still hasn't hit a homer, wtf)",
        "Mason Miller allowed two base runners for the first time all season but who fucking cares, he's the best pitcher in the league and it was never in doubt once he came in. LETS GO DADS, 4-1 final score.",
      ],
    },
  ],
};
