const REPORT = {
  record: { w:19, l:11 },
  nextGames: [
    { date:"FRI MAY 1",  time:"6:40 PM PT",  matchup:"SD Padres vs Chicago White Sox",  venue:"Petco Park"  },
    { date:"SAT MAY 2",  time:"5:40 PM PT",  matchup:"SD Padres vs Chicago White Sox",  venue:"Petco Park"  },
    { date:"SUN MAY 3",  time:"1:10 PM PT",  matchup:"SD Padres vs Chicago White Sox",  venue:"Petco Park"  },
    { date:"MON MAY 4",  time:"6:45 PM PT",  matchup:"SD Padres @ San Francisco Giants", venue:"Oracle Park" },
    { date:"TUE MAY 5",  time:"6:45 PM PT",  matchup:"SD Padres @ San Francisco Giants", venue:"Oracle Park" },
    { date:"WED MAY 6",  time:"12:45 PM PT", matchup:"SD Padres @ San Francisco Giants", venue:"Oracle Park" },
  ],
  entries: [
    {
      type:"recap", gameLabel:"Game #30", gameDate:"WED, APRIL 30", venue:"PETCO PARK, SAN DIEGO",
      result:"L",
      away:{ abbr:"CHC", city:"CHICAGO",   name:"CUBS"   },
      home:{ abbr:"SD",  city:"SAN DIEGO", name:"PADRES" },
      awayScore:5, homeScore:4, winnerIsHome:false,
      linescore:{
        innings:["1","2","3","4","5","6","7","8","9"],
        away:   ["0","1","0","2","0","1","0","1","0"],
        home:   ["0","0","0","0","3","0","0","1","0"],
        awayTotals:{ R:"5", H:"9", E:"0" },
        homeTotals:{ R:"4", H:"3", E:"0" },
      },
      stats:[
        { label:"WP",        value:"Taillon (7 IP, 3 H, 3 ER, 6 K)", type:"win"     },
        { label:"LP",        value:"Morejon",                         type:"loss"    },
        { label:"SV",        value:"Milner",                          type:"win"     },
        { label:"Waldron",   value:"5 IP, 6 H, 3 ER",                type:"neutral" },
        { label:"Castellanos",value:"HR, 2 RBI",                      type:"neutral" },
        { label:"Andújar",   value:"HR, 1 RBI",                       type:"neutral" },
        { label:"Crow-Armstrong (CHC)", value:"HR, 3 RBI",            type:"neutral" },
        { label:"Adam",      value:"1 IP, 1 HR, 1 ER",               type:"neutral" },
      ],
      paragraphs:[
        "Now this one hurt. We had all the chances in the world to win this game and we didn't. Just bad baseball. Padres got 0-3 with RISP, we have bases loaded with no outs in the 8th and score 1 run. That's just awful.",
        "Waldron, similar to Buehler, has neither a good nor bad start. That's okay, that's what we expect. What we cannot have is Manny, Tatis, and Jackson going 1-10 in this game. What's been underrated behind Tatis' extremely slow start to the year is that Jackson has been probably even worse so far. Tatis' underlying metrics indicate he's going to start raking soon, but Jackson's are just flat out bad. Not ideal.",
        "We have every chance to win this game, the Cubbies starter goes absolutely insane and goes 7 IP and only gives up 3 hits, and we still could've won. This team is good and they fight. Just a tough series to lose at home and we NEED the stars to start playing like stars ASAP or this will not be good. Good news though, we got a meh White Sox team coming to town. Let's stack some Ws boys.",
      ],
    },
    {
      type:"recap", gameLabel:"Game #29", gameDate:"TUE, APRIL 29", venue:"PETCO PARK, SAN DIEGO",
      result:"L",
      away:{ abbr:"CHC", city:"CHICAGO",   name:"CUBS"   },
      home:{ abbr:"SD",  city:"SAN DIEGO", name:"PADRES" },
      awayScore:8, homeScore:3, winnerIsHome:false,
      linescore:{
        innings:["1","2","3","4","5","6","7","8","9"],
        away:   ["0","2","0","0","0","2","4","0","0"],
        home:   ["0","1","0","1","0","1","0","0","0"],
        awayTotals:{ R:"8", H:"8", E:"0" },
        homeTotals:{ R:"3", H:"6", E:"1" },
      },
      stats:[
        { label:"WP",        value:"Cabrera (5.2 IP, 6 H, 3 ER, 7 K)", type:"win"     },
        { label:"LP",        value:"Kyle Hart",                          type:"loss"    },
        { label:"Buehler",   value:"4.2 IP, 3 H, 2 ER, 4 K",           type:"neutral" },
        { label:"Bogaerts",  value:"HR, 1 RBI",                         type:"neutral" },
        { label:"Crow-Armstrong (CHC)", value:"HR, 3 RBI",              type:"neutral" },
        { label:"Tatis Jr.", value:"0-4",                               type:"neutral" },
        { label:"Merrill",   value:"0-4",                               type:"neutral" },
      ],
      paragraphs:[
        "So this game is closer than the box score shows. This game was tied 3-3 going into the 6th, and was 4-3 Cubbies going into the 8th. Anyone's game still. Unfortunately, we gave up a 3 HR to Pete Crow Armstrong who either has the best name ever or the worst name ever. He also looks like a white nationalist but who are we to judge.",
        "The fact of the matter is that Walker Buehler didn't have a bad nor good start, and our stars are continuing to not show up. Manny had the day off, and Fernando and Jackson went 0-8 combined. We aren't going to win a lot of games if Walker Buehler only goes 4.2 IP and our boys can't score runs. Competitive game, but not enough vs a good team here.",
      ],
    },
    {
      type:"recap", gameLabel:"Game #28", gameDate:"MON, APRIL 28", venue:"PETCO PARK, SAN DIEGO",
      result:"W",
      away:{ abbr:"CHC", city:"CHICAGO",   name:"CUBS"   },
      home:{ abbr:"SD",  city:"SAN DIEGO", name:"PADRES" },
      awayScore:7, homeScore:9, winnerIsHome:true,
      linescore:{
        innings:["1","2","3","4","5","6","7","8","9"],
        away:   ["0","1","4","0","0","0","0","0","2"],
        home:   ["3","0","1","0","2","0","2","1","X"],
        awayTotals:{ R:"7", H:"8",  E:"0" },
        homeTotals:{ R:"9", H:"14", E:"0" },
      },
      stats:[
        { label:"WP",       value:"Vásquez (5 IP, 5 ER, 4 K)",  type:"win"     },
        { label:"LP",       value:"Ben Brown",                   type:"loss"    },
        { label:"Ty France",value:"2-5, 2B, 3B, 4 RBI",         type:"neutral" },
        { label:"Machado",  value:"3-4, 2 2B, 3 R",             type:"neutral" },
        { label:"Sheets",   value:"HR (2 out, 2 strike, 8th)",  type:"neutral" },
        { label:"Morejon",  value:"1.2 IP, 0 ER, 2 K",          type:"neutral" },
        { label:"Adam",     value:"1.1 IP, 0 ER, 1 K",          type:"neutral" },
        { label:"Miller",   value:"1 IP, 2 ER (streak ends)",    type:"neutral" },
      ],
      paragraphs:[
        "So let start off by saying that Laines and I went to this game and it was ELECTRIC. The vibes started off so high with a 3 run 1st inning. Ty France was 5 feet short of hitting a grand slam, but we'll settle for a 2 RBI double.",
        "Randy V had a pretty rough outing, giving up 5 runs thru 5 IP, but he still gets the W in this one. The defense was also shaky in this game, but it didn't matter because we scored 9 runs in this game. Manny is starting to get hot too, he hit 2 doubles in this game before leaving for precautionary reasons. The precautionary reason is he is so fat that sliding into second twice hurt his hamstrings. Laines even made a comment watching the replay on the big screen that he had that pufferfish, teeth clenched look in the face while sprinting as fast as he could to 2nd (he wasnt moving that fast, he was trying his best tho, really hope he's all healthy and set for tomorrow.)",
        "MVP of the game on offense was Ty France. He had a double, a triple, and 4 RBI in this game. Best cheap bat of the season so far and it's not even close. He's an above average defender with the glove too so we are cooking with gas with this fella.",
        "Adrian Morejon came in in the 6th and shut em down for 1.2 IP, Jason Adam came in and shut em down for 1.1 IP, and then the story of this game came.",
        "Mason Miller comes in because he was the only one warmed up considering the game was 8-5 with 2 outs in the 8th. Then Gavin Sheets who came in for Manny hit a homer with 2 strikes 2 outs in the bottom of the 8th. Hence making the game 9-5. Xander gets out immediately after, and nobody else is warmed up in the bullpen so we have to put Mason Miller in in a non-save situation. Not ideal. The vibes were off, and they didn't even do his sick ass entrance because we all didn't even realize he was coming in in a non-save situation. Then his very first batter, the umpire makes one of the worst calls you'll see this entire baseball season. See the below image.",
        "That is the baseball on the foul side of the line before it gets picked up. The umpire called that ball fair, and it's not reviewable so the leadoff runner was on. The call was so horrific it threw off Miller, eventually leading to him giving up 2 runs and ending his record setting scoreless streak. Just absolutely disgusting. Don't worry though, we all did our job in Petco and boo'd the umpire for the entirety of the next 3 at bats (which probably didn't help Miller either.) Anyways, he got the final 3 outs and doesn't get a save but we win so whatever. Dads 9-7, we focus on that and aim at getting a series W by winning tomorrow. Dads have won a few in a row at home, let's keep that going!",
      ],
      photo: "https://maxbish.github.io/PadresReport/pictures/horriblecall.JPG",
      photoCaption: "That ball is foul. Not reviewable. Criminal.",
    },
    {
      type:"recap", gameLabel:"Game #27", gameDate:"SUN, APRIL 27", venue:"MEXICO CITY, MEXICO",
      result:"L",
      away:{ abbr:"SD", city:"SAN DIEGO", name:"PADRES"      },
      home:{ abbr:"AZ", city:"ARIZONA",   name:"DIAMONDBACKS" },
      awayScore:7, homeScore:12, winnerIsHome:true,
      linescore:{
        innings:["1","2","3","4","5","6","7","8","9"],
        away:   ["0","1","2","0","3","1","0","0","0"],
        home:   ["0","0","0","0","1","1","6","4","X"],
        awayTotals:{ R:"7",  H:"11", E:"0" },
        homeTotals:{ R:"12", H:"15", E:"1" },
      },
      stats:[
        { label:"WP",          value:"Thompson",             type:"win"     },
        { label:"LP",          value:"B. Rodriguez",          type:"loss"    },
        { label:"King",        value:"6 IP, 3 H, 2 ER, 8 K", type:"neutral" },
        { label:"Machado",     value:"2 HR, 5 RBI",           type:"neutral" },
        { label:"Campusano",   value:"2-4, HR, 2B, 2 RBI",   type:"neutral" },
        { label:"Marinaccio",  value:"0.1 IP, 5 H, 4 ER",    type:"loss"    },
        { label:"D. Morgan",   value:"0.1 IP, 4 H, 4 ER",    type:"loss"    },
        { label:"Vargas (AZ)", value:"3-5, GS, 4 RBI",       type:"neutral" },
      ],
      paragraphs:[
        "Well that was an incredibly strange and shitty game today.",
        "The Dads just straight up dominated for 6 innings today. Michael King dominated, Manny Machado took advantage of some high elevation, and Luis Campusano had another day worth talking about.",
        "Michael King gave up 3 hits (2 being home runs, thanks Mexico City) thru 6 IP and struck out 8. Pretty sure there was a point in this game where he had struck out 7 of the previous 8 batters. Just an elite day from our guy. Control looks shaky at times but if he stays healthy, he'll be a force for us all year long.",
        "Meanwhile, Manny heard me making fun of him for being fat and decided to use that fat ass to smash two balls out of the park. 2 HR, 5 RBI day for Manny, sheesh. Campy also hit a HR and had 2 RBI today, one coming on a double and the other the HR. He's no longer just dominating AAA, he's been straight up dominating MLB pitchers and thats a GREAT sign for this ballclub.",
        "Dads lead 7-2 heading into the bottom of the 7th..",
        "Unfortunately, that worry that I mentioned previously about our bullpen came to rear its ugly, disgusting, repulsive head today. Morejon and Adam didn't pitch, and as a result, the Padres bullpen gave up 10 runs and 12 hits in the 7th and 8th inning combined. This game went from cruise control for the Dads, to a holy fucking shit, we're losing 12-7 in a real heartbeat. I don't think we'll see another outing like this one from our bullpen, the DBacks also took insane advantage of Mexico City literally being heaven for batters (and it might literally be heaven in general because of the altitude.) They had a guy hit his first career grand slam today and I guarantee that ball is not leaving the ballpark in Petco or Arizona.",
        "Shit happens, sometimes you fluke and sometimes you get fluked. We let it go, split the season series, and focus up on a BIG series vs another good team in the Cubbies at home.",
        "See you all tomorrow. Mara or Kyler, if you're reading this, text me your favorite color ASAP or else I'm going to complain that you aren't reading my daddies report. 😭",
      ],
    },
    {
      type:"recap", gameLabel:"Game #26", gameDate:"SAT, APRIL 26", venue:"MEXICO CITY, MEXICO",
      result:"W", seriesResult:"W",
      away:{ abbr:"SD", city:"SAN DIEGO", name:"PADRES"      },
      home:{ abbr:"AZ", city:"ARIZONA",   name:"DIAMONDBACKS" },
      awayScore:6, homeScore:4, winnerIsHome:false,
      linescore:{
        innings:["1","2","3","4","5","6","7","8","9"],
        away:   ["0","0","0","0","1","0","4","0","1"],
        home:   ["0","4","0","0","0","0","0","0","0"],
        awayTotals:{ R:"6", H:"6", E:"1" },
        homeTotals:{ R:"4", H:"7", E:"3" },
      },
      stats:[
        { label:"WP",        value:"Márquez (6 IP, 4 ER)",      type:"win"     },
        { label:"LP",        value:"Clarke",                     type:"loss"    },
        { label:"SV",        value:"Miller (13 P, 1 IP, 0 ER)", type:"win"     },
        { label:"Ty France", value:"2-4, 2 HR, 2 RBI",          type:"neutral" },
        { label:"Sheets",    value:"2 RBI single",               type:"neutral" },
        { label:"Waldron",   value:"5 IP, 6 ER",                 type:"neutral" },
      ],
      paragraphs:[
        "Life comes at you fast. It comes at you even faster if the German Meatball is pitching in Mexico City. He threw 5 outs, decided he was pitching TOO well, and it was time to get some meatballs involved. He then gave up 4 consecutive runs with 2 outs in the 2nd. Thankfully mr meatball locked in and didnt give up another run in his outing thru 6 innings. Mr Meatball in all honesty has been pitching like so much better than what we were all expecting out of him this season. Morejon got the nod in the 7th and did his thing (his thing includes two runners getting on base but also striking out two batters, i love him so much). Jason Adam got the nod in the 8th. He continues to have little control over his fastball but every other pitch is elite. Mason Miller came in for the 9th to close this game out and did just that. He sets the franchise record for most consecutive innings pitched without giving up a score. MVP. If our starting pitching can get through 6 innings consistently, the Morejon Adam Miller ending rotation is so incredibly dominant.",
        "Fortunately, life comes at you the fastest if you're the Diamondbacks playing in Mexico City. Their starting pitcher got hit by a ball after Fermin hit the ball back at him and railed him in his throwing shoulder. He had to leave the game. Their starting shortstop also rolled his ankle and got actually hurt in the 7th (in honor of the NFL draft, I thought he had torn his Achilles at first.) He had to leave the game. And best of all, all the fans in Mexico City fucking hate the DBacks and love the Padres. Say what you want, but Mexico City people and I would all be best friends considering we love the Niners and the Padres.",
        "This Padres offense is hilarious. They do absolutely nothing for 7-8 innings a game but then blow up out of nowhere to score enough runs to win the game all in 1-2 innings. We had the bases loaded TWICE with no outs in just the 7th inning alone, and Gavin Sheets continues to be a baller shot caller (2 RBI single in the 7th). 4 run 7th inning no big deal. Fun fact, Jackson Merrill got to bat twice in the 7th (he started the inning with a walk and then ended the inning as the last out.) Ty France also homered twice this game lmao. Elevation diff.",
        "All in all, this was one of the games played in Mexico City of all time. Fun Fact x2: Mexico City is 7,300+ ft above sea level (clears Denver by 1,800+ ft). If Fernando cant hit a home run tomorrow, we might as well just accept he's never going to hit another homer ever again. The Dads do be out here getting their conditioning in at this high elevation, which I love but is also Manny's personal hell. Do you know what Manny and I both love though? A Padres victory, 6-4. A great victory against a team that we'll be competing with for a postseason spot, let's get another one tomorrow.",
      ],
    },
    {
      type:"recap", gameLabel:"Game #25", gameDate:"THU, APRIL 24", venue:"COORS FIELD, DENVER",
      result:"W", seriesResult:"SERIES W 2-1",
      away:{ abbr:"SD",  city:"SAN DIEGO", name:"PADRES"  },
      home:{ abbr:"COL", city:"COLORADO",  name:"ROCKIES" },
      awayScore:10, homeScore:8, winnerIsHome:false,
      linescore:{
        innings:["1","2","3","4","5","6","7","8","9"],
        away:   ["0","0","0","2","0","2","0","1","5"],
        home:   ["0","3","0","0","3","0","2","0","0"],
        awayTotals:{ R:"10", H:"12", E:"0" },
        homeTotals:{ R:"8",  H:"11", E:"0" },
      },
      stats:[
        { label:"WP",       value:"Marinaccio",                 type:"win"     },
        { label:"SV",       value:"Miller",                     type:"win"     },
        { label:"LP",       value:"Vodnik",                     type:"loss"    },
        { label:"Sheets",   value:"3-run HR, go-ahead in 9th",  type:"neutral" },
        { label:"Andújar",  value:"2 RBI, key singles",         type:"neutral" },
        { label:"Bogaerts", value:"multi-hit",                  type:"neutral" },
        { label:"Waldron",  value:"5 IP, 6 ER",                 type:"neutral" },
      ],
      paragraphs:[
        "HOLY SHEETS. What a game. If you are an absolute loser and a mindless, employed sheep of society, you probably didnt catch this game (I couldnt watch either). And boy oh boy, did we miss out.",
        "Let's start with the bad. I made a comment about our starting pitching being elite to start the season at the beginning of this series. That turned out to be just a wittle bit of a lie. Turns out that Matt Waldron should probably go back to just trying to throw a knuckleball 90% of the time and hope it doesn't get smashed. Waldron went 5 innings and gave up more runs than innings pitched, but we're not here to talk about that.",
        "This game was 8-4 going into the 8th in favor of the Rockies and things felt worse. The Rockies were racking, Morejon gave up a homer (Rockies are cheating, it's obvious), and while we had scored some runs, the bats were just not showing up. Merrill up to that point had 3 strikeouts on 3 plate appearances just to share the feeling of how this one was going.",
        "However, this team has some mother freaking fight in them. We score a run in the 8th. Tatis even had a chance at hitting a 3 run HR in the 8th to tie this game up, but nah, strikeout for Tatis. That doesn't matter tho (it actually does and I'll expand on that later). Ron Marinaccio shuts down the Rockies in the bottom of the 8th.",
        "Then all hell breaks loose. Jackson Merrill decides he's tired of striking out today and gets a lead off walk. Manny singles. The summer of Xan continues and he singles (driving in Jackson). Miguel Andujar and Xander legit carried this team offensively today, and Miggy singles to score Manny. And then, the birthday boy arrives. Gavin mfing Sheets walks up there, and on the first pitch screams \"I fucking HATE losing\" and he rips a ball down the right field line and it is GONE. 3 RUN HOMER to take a 10-8 lead. At that point, the game might as well end because we have Mason Miller.",
        "Mason Miller comes in for the save attempt, gives up 1 hit strangely enough to the second batter, but ends up throwing 7 total pitches to get 3 outs in the bottom of the 9th to close this game and series out. Padres win 10-8, Mason Miller gets the save (didn't throw a strikeout so he's not winning the Cy Young award anymore sadly), and the Dads win the series on the road 2-1.",
        "As insane of a victory as I can remember for this season so far. So I want to take this time to send a message to our friend Fernando. Whenever you feel like being a professional hitter again for this Padres team, that'd be really dope because we're basically unbeatable when you get your swagger back.",
        "Up next: Short 2 game series vs the DBacks in Zona and we need wins against this team, both division wise and wild card race wise. Let's go Dads!",
      ],
      photo: "https://maxbish.github.io/PadresReport/pictures/xander1.webp",
      photoCaption: "The Summer of Xan continues.",
    },
    {
      type:"recap", gameLabel:"Game #24", gameDate:"WED, APRIL 22", venue:"COORS FIELD, DENVER",
      result:"L",
      away:{ abbr:"SD",  city:"SAN DIEGO", name:"PADRES"  },
      home:{ abbr:"COL", city:"COLORADO",  name:"ROCKIES" },
      awayScore:3, homeScore:8, winnerIsHome:true,
      linescore:{
        innings:["1","2","3","4","5","6","7","8","9"],
        away:   ["1","0","0","0","0","0","1","0","1"],
        home:   ["0","4","0","1","0","1","1","1","—"],
        awayTotals:{ R:"3", H:"7",  E:"0" },
        homeTotals:{ R:"8", H:"15", E:"1" },
      },
      stats:[
        { label:"WP",          value:"Sugano",                          type:"win"     },
        { label:"LP",          value:"W. Buehler (2.2 IP, 8 H, 4 ER)", type:"loss"    },
        { label:"Campusano",   value:"3-4, HR, 2 2B, RBI",              type:"neutral" },
        { label:"Bogaerts",    value:"2-4",                             type:"neutral" },
        { label:"Merrill",     value:"RBI",                             type:"neutral" },
        { label:"Buehler ERA", value:"13.50",                           type:"neutral" },
      ],
      paragraphs:[
        "We witnessed a miracle today. This must've been what it felt like when we landed on the moon, when we discovered the cure to polio, etc etc. The Padres scored a run in the 1st inning! Of course it was due to The Magnificent Merrill and his beautiful textbook single to drive in Laureano.",
        "However, this euphoric feeling did not last because washed ass Walker Buehler summoned his Dodgers DNA and got lit the fuck up for 4 runs in the 2nd inning. A little fishy if you ask me. He got pulled after 3 innings. It was a rough game, bullpen got used a lot.",
        "Unfortunately, overcoming a 4-1 deficit is just not in this team's DNA currently. We scored 2 more but not before they added 4 more runs to their total. Dads lose, but that's okay. Cant win em all.",
      ],
    },
    {
      type:"recap", gameLabel:"Game #23", gameDate:"TUE, APRIL 21", venue:"COORS FIELD, DENVER",
      result:"W",
      away:{ abbr:"SD",  city:"SAN DIEGO", name:"PADRES"  },
      home:{ abbr:"COL", city:"COLORADO",  name:"ROCKIES" },
      awayScore:1, homeScore:0, winnerIsHome:false,
      linescore:{
        innings:["1","2","3","4","5","6","7","8","9"],
        away:   ["0","0","0","0","0","1","0","0","0"],
        home:   ["0","0","0","0","0","0","0","0","0"],
        awayTotals:{ R:"1", H:"6", E:"0" },
        homeTotals:{ R:"0", H:"3", E:"1" },
      },
      stats:[
        { label:"WP",           value:"Vásquez (7 IP, 3 H, 0 ER, 5 K)", type:"win"     },
        { label:"SV",           value:"Morején (2 K)",                   type:"win"     },
        { label:"Machado",      value:"walk-off RBI walk, bases loaded",  type:"neutral" },
        { label:"Tatis Jr.",    value:"2-4",                             type:"neutral" },
        { label:"COL Ks",       value:"15",                              type:"neutral" },
        { label:"Dollander LP", value:"9 K, 6 IP, 1 ER",                type:"loss"    },
      ],
      paragraphs:[
        "An unstoppable force meets an extremely movable object. The Padres offense continues to roll, as they mustered ONE whole run in this game. The Rockies stadium is well known to lend itself to some insanely high scoring games due to its smaller size and the high elevation in Colorado (the ball goes farther, it just does). You'll be shocked to hear then that the Rockies pitchers threw 15 strikeouts. Maybe they were cheating and drilled holes in the Dads' bats, more to come on this theory as the series continues.",
        "Good news tho, the Rockies cant cheat their way around the rules. They fell for the ultimate Dads trap. Bases loaded, full 3-2 count, 2 outs, Manny Machado up to bat, and the Rockies feel his immense fat ass aura and walk him, hence also walking in the only run of the day. DOMINATING OFFENSE.",
        "Randy Vasquez continues to start the season extremely strong, and is probably our #1 right now. He goes 7 IP, only giving up 3 hits. Our starting pitching is elite, which is actually the most insane thing about the start of this season so far.",
        "We decided we didnt need Mason Miller to close this game, so Adrian Morejon came in, struck out two immediately, and then almost gave up a home run but it was caught by our lord and savior Jackson Merrill well short of the fence. Padres dominate the Rockies 1-0. All we do is win, win, win.",
      ],
    },
    {
      type:"offday", gameLabel:"Off Day", offDaySub:"BEFORE THE COLORADO SERIES", result:"OFF",
      paragraphs:[
        "We did not play a game today, therefore we are just a 0.5 game back of the Dodgers as I type this.",
        "However, the Dodgers do play today and are beating the Rockies currently so standings subject to change. The Dodgers also baselessly accused the Rockies of cheating this past weekend, because it is absolutely ridiculous to think that a team can win their own home stadium against a 1 billion dollar roster. With that being said, the Padres are kicking off their series against the Rockies in Colorado tomorrow so stand up and stand by in case we jump onto the bandwagon and also accuse them of cheating.",
      ],
    },
    {
      type:"recap", gameLabel:"Game #22", gameDate:"SUN, APRIL 19", venue:"ANGEL STADIUM, ANAHEIM",
      result:"W", seriesResult:"SERIES W 2-1",
      away:{ abbr:"SD",  city:"SAN DIEGO",   name:"PADRES" },
      home:{ abbr:"LAA", city:"LOS ANGELES", name:"ANGELS" },
      awayScore:2, homeScore:1, winnerIsHome:false,
      linescore:null, stats:[],
      paragraphs:[
        "The Dads' offense continues to an unstoppable force of nature, putting up 2 whole runs in this game. When you get contributions from Bryce Johnson at the plate, feels like a victory is all but guaranteed.",
        "Michael King continues to be very good. That signed ball by Mr King that Laines won during opening weekend is just gaining more and more value, so we will continue to trust our ace every time he takes the mound. I wonder if we'll be able to exchange that ball for some raw, beautiful, malleable gold.",
        "Something that is not being talked about is that anybody not named Adrian Morejon or Mason Miller scares the ever living shit out of me when they go to the bullpen. Jason Adam will figure it out because he's a god fearing conservative white man, but everybody else makes me nervous right now.",
        "Mason Miller is the GOAT. The Dads win 2-1 and win the series 2-1. Happy church day and to all a good nap.",
      ],
    },
    {
      type:"recap", gameLabel:"Game #21", gameDate:"SAT, APRIL 18", venue:"ANGEL STADIUM, ANAHEIM",
      result:"W", seriesResult:"W 4-1",
      away:{ abbr:"SD",  city:"SAN DIEGO",   name:"PADRES"  },
      home:{ abbr:"LAA", city:"LOS ANGELES", name:"ANGELS"  },
      awayScore:4, homeScore:1, winnerIsHome:false,
      linescore:null, stats:[],
      paragraphs:[
        "Our starting pitcher was German Marquez, who I call the German Meatball. He is not German, but he does throw meatballs. Thankfully, no balls left the park vs him today as he went 5 and 2/3 IPs allowing only 2 hits.",
        "While the german meatball was out there proving that the Angels are in fact ass, we are also ass because this game was 0-0 going into the 8th inning. Thankfully, we scored 2 runs on two of the softest hits that I have ever seen and its better to be lucky than good. We added on to our lead in the 9th the same exact way, but at least Tatis drove some runs home (he still hasn't hit a homer, wtf)",
        "Mason Miller allowed two base runners for the first time all season but who fucking cares, he's the best pitcher in the league and it was never in doubt once he came in. LETS GO DADS, 4-1 final score.",
      ],
    },
  ],
};
